//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point3_1
	{
		public static Vector3 begin1 = new Vector3 (9.89f, 1.0F, 3.81f);//
		public static Vector3 begin2 = new Vector3 (-10.41f, 1.0F, -4.81F);
		public static Vector3 start = new Vector3 (-0.4f, 1.0F, -0.1f);
		public static Vector3 evalator = new Vector3 (-0.4f, 1.0F, -2.99f);
		
		public static Vector3 evalator1 = new Vector3 (21.79f, 1.0F, 4.18f);
		public static Vector3 evalator2 = new Vector3 (-20.63f, 1.0F, -5.13f);
		
		public static Vector3 p2 = new Vector3 (-10.41f, 1.0F, -0.1f);
		public static Vector3 p1 = new Vector3 (9.89f, 1.0F, -0.1f);
		public static Vector3 p3 = new Vector3 (-20.63f, 1.0F, -0.1f);
		public static Vector3 p4 = new Vector3 (21.79f, 1.0F, -0.1f);
		
		static Vector3[] thangmay = new Vector3[] { begin1, p1, start, evalator };	//
		static Vector3[] thangmay1 = new Vector3[] { begin1, p1, p4, evalator1 };//
		static Vector3[] thangmay2 = new Vector3[] { begin2, p2, p3, evalator2 };	
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Point3_1 ()
		{
			dictionary.Add ("thangmay", thangmay);
			dictionary.Add ("thangkeo1", thangmay1);
			dictionary.Add ("thangkeo2", thangmay2);
		}
	}
}

