//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point5_2handicap
	{
		public static Vector3 evalator1 = new Vector3 (21.79f, 1.5f, 4.18f);
		public static Vector3 evalator2 = new Vector3 (-20.63f, 1.5f, -5.13f);

		static Vector3 o1 = new Vector3 (25.8F, 3.8F, 16.3F);
		static Vector3 o2 = new Vector3 (9.0F, 3.8F, 10.4F);
		static Vector3 o3 = new Vector3 (16.7F, 3.8F, -7.1F);
		static Vector3 o4 = new Vector3 (33.5F, 3.8F, -0.6F);
		static Vector3 o5 = new Vector3 (-17.3F, 3.8F, 6.6F);
		static Vector3 o6 = new Vector3 (-34.1F, 3.8F, 0.7F);
		static Vector3 o7 = new Vector3 (-26.5F, 3.8F, -16.8F);
		static Vector3 o8 = new Vector3 (-9.7F, 3.8F, -10.3F);
		
		
		static Vector3 f1 = new Vector3 (25.8F, 3.8F, 8.27F);
		static Vector3 f2 = new Vector3 (16.7F, 3.8F, 10.4F);
		static Vector3 f3 = new Vector3 (16.7F, 3.8F, -0.1F);
		static Vector3 f4 = new Vector3 (26.32F, 3.8F, -0.1F);
		static Vector3 f5 = new Vector3 (-17.3F, 3.8F, -0.1F);
		static Vector3 f6 = new Vector3 (-26.71F, 3.8F, -0.1F);
		static Vector3 f7 = new Vector3 (-26.5F, 3.8F, -8.9F);
		static Vector3 f8 = new Vector3 (-17.3F, 3.8F, -10.3F);
		
		
		static Vector3[] office1 = new Vector3[] { evalator1, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, f3, o3 };		
		static Vector3[] office4 = new Vector3[] { evalator1, f4, o4 };
		
		static Vector3[] office5 = new Vector3[] { evalator2, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator2, f6, o6 };		
		static Vector3[] office7 = new Vector3[] { evalator2, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator2, f8, o8 };
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();

		public Point5_2handicap ()
		{			
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
		}
	}
}

