//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point4_4handicap
	{
		
		public static Vector3 evalator1 = new Vector3 (21.79f, 1.0F, 4.18f);
		public static Vector3 evalator2 = new Vector3 (-20.63f, 1.0F, -5.13f);

		static Vector3 o1 = new Vector3 (25.2F, 1.0F, 13.4F);
		static Vector3 o2 = new Vector3 (11.6F, 1.0F, 7.7F);
		static Vector3 o3 = new Vector3 (17.6F, 1.0F, -4.8F);
		static Vector3 o4 = new Vector3 (31.2F, 1.0F, 0.7F);
		static Vector3 o5 = new Vector3 (-17.8F, 1.0F, 3.7F);
		static Vector3 o6 = new Vector3 (-31.4F, 1.0F, -2.0F);
		static Vector3 o7 = new Vector3 (-25.4F, 1.0F, -14.5F);
		static Vector3 o8 = new Vector3 (-11.8F, 1.0F, -9.0F);
		
		static Vector3 f1 = new Vector3 (25.2F, 1.0F, 9.0F);
		static Vector3 f2 = new Vector3 (17.6F, 1.0F, 7.7F);
		static Vector3 f3 = new Vector3 (17.6F, 1.0F, -0.5F);
		static Vector3 f4 = new Vector3 (26.9F, 1.0F, -0.5F);
		static Vector3 f5 = new Vector3 (-16.2F, 1.0F, -0.5F);
		static Vector3 f6 = new Vector3 (-27.1F, 1.0F, -0.5F);
		static Vector3 f7 = new Vector3 (-25.4F, 1.0F, -10.2F);
		static Vector3 f8 = new Vector3 (-16.2F, 1.0F, -9.0F);
		
		
		static Vector3[] office1 = new Vector3[] { evalator1, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, f3, o3 };		
		static Vector3[] office4 = new Vector3[] { evalator1, f4, o4 };
		
		static Vector3[] office5 = new Vector3[] { evalator2, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator2, f6, o6 };		
		static Vector3[] office7 = new Vector3[] { evalator2, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator2, f8, o8 };

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();

		public Point4_4handicap ()
		{
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
		}
	}
}

