//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point2_4
	{
		static Vector3 evalator = new Vector3 (0.0f, 0.0f, -2.6f);
		static Vector3 start = new Vector3 (0.0f, 0.0f, 0.0f);
		
		static Vector3 f1 = new Vector3 (25.9F, 2.5F, 9.4F);
		static Vector3 f2 = new Vector3 (22.0F, 2.5F, 9.4F);
		static Vector3 f3 = new Vector3 (18.1F, 2.5F, 9.4F);
		static Vector3 f4 = new Vector3 (14.1F, 2.5F, 9.4F);
		static Vector3 f5 = new Vector3 (14.1F, 2.5F, 9.4F);
		static Vector3 f6 = new Vector3 (14.5F, 2.5F, 6.6F);
		static Vector3 f7 = new Vector3 (14.5F, 2.5F, 2.7F);
		static Vector3 f8 = new Vector3 (10.2F, 2.5F, 0.0F);
		static Vector3 f9 = new Vector3 (14.1F, 2.5F, -0.1F);
		static Vector3 f10 = new Vector3 (18.0F, 2.5F, -0.1F);
		static Vector3 f11 = new Vector3 (21.9F, 2.5F, -0.1F);
		static Vector3 f12 = new Vector3 (25.8F, 2.5F, -0.1F);
		static Vector3 f13 = new Vector3 (25.8F, 2.5F, -0.1F);
		static Vector3 f14 = new Vector3 (25.5F, 2.5F, 2.7F);
		static Vector3 f15 = new Vector3 (25.5F, 2.5F, 6.6F);
		static Vector3 f16 = new Vector3 (25.9F, 2.5F, 9.4F);
		static Vector3 f17 = new Vector3 (-13.3F, 2.5F, -0.4F);
		static Vector3 f18 = new Vector3 (-17.3F, 2.5F, -0.2F);
		static Vector3 f19 = new Vector3 (-21.2F, 2.5F, -0.2F);
		static Vector3 f20 = new Vector3 (-25.1F, 2.5F, -0.2F);
		static Vector3 f21 = new Vector3 (-29.1F, 2.5F, -0.2F);
		static Vector3 f22 = new Vector3 (-29.1F, 2.5F, -0.2F);
		static Vector3 f23 = new Vector3 (-28.6F, 2.5F, -3.0F);
		static Vector3 f24 = new Vector3 (-28.6F, 2.5F, -6.9F);
		static Vector3 f25 = new Vector3 (-29.1F, 2.5F, -9.7F);
		static Vector3 f26 = new Vector3 (-29.1F, 2.5F, -9.7F);
		static Vector3 f27 = new Vector3 (-25.2F, 2.5F, -9.7F);
		static Vector3 f28 = new Vector3 (-21.2F, 2.5F, -9.7F);
		static Vector3 f29 = new Vector3 (-17.3F, 2.5F, -9.7F);
		static Vector3 f30 = new Vector3 (-17.3F, 2.5F, -9.7F);
		static Vector3 f31 = new Vector3 (-17.7F, 2.5F, -6.9F);
		static Vector3 f32 = new Vector3 (-17.7F, 2.5F, -3.0F);

		
		static Vector3 o1 = new Vector3 (25.9F, 2.5F, 13.7F);
		static Vector3 o2 = new Vector3 (22.0F, 2.5F, 13.7F);
		static Vector3 o3 = new Vector3 (18.1F, 2.5F, 13.7F);
		static Vector3 o4 = new Vector3 (14.1F, 2.5F, 13.7F);
		static Vector3 o5 = new Vector3 (9.7F, 2.5F, 12.2F);
		static Vector3 o6 = new Vector3 (10.2F, 2.5F, 6.6F);
		static Vector3 o7 = new Vector3 (10.2F, 2.5F, 2.7F);
		static Vector3 o8 = new Vector3 (10.2F, 2.5F, -4.3F);
		static Vector3 o9 = new Vector3 (14.1F, 2.5F, -4.4F);
		static Vector3 o10 = new Vector3 (18.0F, 2.5F, -4.4F);
		static Vector3 o11 = new Vector3 (21.9F, 2.5F, -4.4F);
		static Vector3 o12 = new Vector3 (25.8F, 2.5F, -4.4F);
		static Vector3 o13 = new Vector3 (30.2F, 2.5F, -2.9F);
		static Vector3 o14 = new Vector3 (29.8F, 2.5F, 2.7F);
		static Vector3 o15 = new Vector3 (29.8F, 2.5F, 6.6F);
		static Vector3 o16 = new Vector3 (30.3F, 2.5F, 12.2F);
		static Vector3 o17 = new Vector3 (-13.3F, 2.5F, 3.9F);
		static Vector3 o18 = new Vector3 (-17.3F, 2.5F, 4.1F);
		static Vector3 o19 = new Vector3 (-21.2F, 2.5F, 4.1F);
		static Vector3 o20 = new Vector3 (-25.1F, 2.5F, 4.1F);
		static Vector3 o21 = new Vector3 (-29.1F, 2.5F, 4.1F);
		static Vector3 o22 = new Vector3 (-33.4F, 2.5F, 2.6F);
		static Vector3 o23 = new Vector3 (-32.9F, 2.5F, -3.0F);
		static Vector3 o24 = new Vector3 (-32.9F, 2.5F, -6.9F);
		static Vector3 o25 = new Vector3 (-33.4F, 2.5F, -12.6F);
		static Vector3 o26 = new Vector3 (-29.1F, 2.5F, -14.1F);
		static Vector3 o27 = new Vector3 (-25.2F, 2.5F, -14.1F);
		static Vector3 o28 = new Vector3 (-21.2F, 2.5F, -14.1F);
		static Vector3 o29 = new Vector3 (-17.3F, 2.5F, -14.1F);
		static Vector3 o30 = new Vector3 (-12.9F, 2.5F, -12.5F);
		static Vector3 o31 = new Vector3 (-13.4F, 2.5F, -6.9F);
		static Vector3 o32 = new Vector3 (-13.4F, 2.5F, -3.0F);

		
		static Vector3 pos1 = new Vector3 (288.0F, 81.8F, 248.0F);
		static Vector3 lookat1 = new Vector3 (290.0F, 6.5F, 191.4F);
		static Vector3 pos2 = new Vector3 (284.1F, 74.4F, 237.2F);
		static Vector3 lookat2 = new Vector3 (287.9F, 6.3F, 189.8F);
		static Vector3 pos3 = new Vector3 (287.2F, 83.3F, 239.3F);
		static Vector3 lookat3 = new Vector3 (288.0F, 7.8F, 189.8F);
		static Vector3 pos4 = new Vector3 (287.1F, 77.6F, 243.6F);
		static Vector3 lookat4 = new Vector3 (285.3F, 2.1F, 189.0F);
		static Vector3 pos5 = new Vector3 (287.3F, 72.3F, 242.2F);
		static Vector3 lookat5 = new Vector3 (287.4F, 5.4F, 188.8F);
		static Vector3 pos6 = new Vector3 (282.5F, 77.8F, 243.7F);
		static Vector3 lookat6 = new Vector3 (284.8F, 10.3F, 187.6F);
		static Vector3 pos7 = new Vector3 (299.9F, 82.7F, 263.4F);
		static Vector3 lookat7 = new Vector3 (286.2F, -5.1F, 186.4F);
		static Vector3 pos8 = new Vector3 (284.9F, 78.7F, 244.1F);
		static Vector3 lookat8 = new Vector3 (284.3F, 0.6F, 185.0F);
		static Vector3 pos9 = new Vector3 (304.2F, 71.4F, 269.6F);
		static Vector3 lookat9 = new Vector3 (291.7F, -0.1F, 184.9F);
		static Vector3 pos10 = new Vector3 (286.5F, 84.7F, 250.1F);
		static Vector3 lookat10 = new Vector3 (288.6F, -2.4F, 184.9F);
		static Vector3 pos12 = new Vector3 (295.1F, 78.9F, 252.0F);
		static Vector3 lookat12 = new Vector3 (294.3F, -2.5F, 184.9F);
		static Vector3 pos13 = new Vector3 (297.2F, 61.7F, 252.7F);
		static Vector3 lookat13 = new Vector3 (294.6F, 1.4F, 185.2F);
		static Vector3 pos14 = new Vector3 (292.6F, 72.2F, 246.8F);
		static Vector3 lookat14 = new Vector3 (294.3F, -0.1F, 186.4F);
		static Vector3 pos15 = new Vector3 (303.4F, 69.9F, 264.5F);
		static Vector3 lookat15 = new Vector3 (286.8F, -6.3F, 187.6F);
		static Vector3 pos16 = new Vector3 (298.5F, 78.1F, 244.8F);
		static Vector3 lookat16 = new Vector3 (291.8F, -2.2F, 189.6F);
		static Vector3 pos17 = new Vector3 (288.5F, 94.7F, 254.0F);
		static Vector3 lookat17 = new Vector3 (288.7F, -2.7F, 187.7F);
		static Vector3 pos18 = new Vector3 (295.6F, 84.7F, 242.1F);
		static Vector3 lookat18 = new Vector3 (293.2F, -8.0F, 186.3F);
		static Vector3 pos19 = new Vector3 (293.9F, 71.4F, 240.9F);
		static Vector3 lookat19 = new Vector3 (293.8F, 0.4F, 186.3F);
		static Vector3 pos20 = new Vector3 (292.0F, 72.4F, 235.8F);
		static Vector3 lookat20 = new Vector3 (293.9F, -1.3F, 186.3F);
		static Vector3 pos21 = new Vector3 (290.7F, 78.3F, 232.7F);
		static Vector3 lookat21 = new Vector3 (291.2F, -1.3F, 186.3F);
		static Vector3 pos22 = new Vector3 (290.2F, 70.4F, 244.5F);
		static Vector3 lookat22 = new Vector3 (291.2F, 1.5F, 186.1F);
		static Vector3 pos24 = new Vector3 (246.9F, 71.1F, 234.1F);
		static Vector3 lookat24 = new Vector3 (276.5F, 7.4F, 183.7F);
		static Vector3 pos25 = new Vector3 (263.9F, 49.9F, 258.3F);
		static Vector3 lookat25 = new Vector3 (286.9F, -2.2F, 181.2F);
		static Vector3 pos26 = new Vector3 (289.5F, 65.6F, 243.9F);
		static Vector3 lookat26 = new Vector3 (290.2F, -0.2F, 180.4F);
		static Vector3 pos27 = new Vector3 (286.9F, 66.7F, 237.3F);
		static Vector3 lookat27 = new Vector3 (294.2F, -1.4F, 181.5F);
		static Vector3 pos28 = new Vector3 (277.0F, 66.5F, 244.5F);
		static Vector3 lookat28 = new Vector3 (292.2F, 1.1F, 181.5F);
		static Vector3 pos29 = new Vector3 (264.4F, 72.9F, 241.9F);
		static Vector3 lookat29 = new Vector3 (286.3F, 4.6F, 182.3F);
		static Vector3 pos30 = new Vector3 (273.9F, 68.5F, 241.8F);
		static Vector3 lookat30 = new Vector3 (290.6F, 0.4F, 182.5F);
		static Vector3 pos31 = new Vector3 (269.1F, 74.0F, 241.7F);
		static Vector3 lookat31 = new Vector3 (287.4F, 6.3F, 183.7F);
		static Vector3 pos32 = new Vector3 (266.8F, 65.1F, 244.2F);
		static Vector3 lookat32 = new Vector3 (289.1F, 5.2F, 184.8F);
		static Vector3 pos23 = new Vector3 (291.5F, 78.0F, 237.5F);
		static Vector3 lookat23 = new Vector3 (288.8F, -5.6F, 184.8F);
		static Vector3 pos11 = new Vector3 (294.7F, 71.5F, 238.0F);
		static Vector3 lookat11 = new Vector3 (294.5F, -3.7F, 184.9F);


		
		
		static Vector3[] office1 = new Vector3[] { evalator, start, f9, f4, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator, start, f9, f4, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator, start, f9, f4, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator, start, f9, f4, o4 };
		static Vector3[] office5 = new Vector3[] { evalator, start, f9, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator, start, f9, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator, start, f9, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator, start, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator, start, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator, start,  f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator, start, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator, start, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator, start, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evalator, start, f12, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator, start, f12, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator, start, f9, f4, f16, o16 };
		static Vector3[] office17 = new Vector3[] { evalator, start, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evalator, start, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evalator, start, f19, o19 };
		static Vector3[] office20 = new Vector3[] { evalator, start, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator, start, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator, start, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evalator, start, f22, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator, start, f22, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator, start, f22, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evalator, start, f18, f29, f26, o26 };
		static Vector3[] office27 = new Vector3[] { evalator, start, f18, f29, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator, start, f18, f29, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator, start, f18, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator, start, f18, f30, o30 };
		
		static Vector3[] office31 = new Vector3[] { evalator, start, f18, f31, o31 };
		static Vector3[] office32 = new Vector3[] { evalator, start, f18, f32, o32 };

		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point2_4 ()
		{
			
			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);
			PositnCamera.Add("office21",pos21);
			PositnCamera.Add("office22",pos22);
			PositnCamera.Add("office23",pos23);
			PositnCamera.Add("office24",pos24);
			PositnCamera.Add("office25",pos25);
			PositnCamera.Add("office26",pos26);
			PositnCamera.Add("office27",pos27);
			PositnCamera.Add("office28",pos28);
			PositnCamera.Add("office29",pos29);
			PositnCamera.Add("office30",pos30);
			PositnCamera.Add("office31",pos31);
			PositnCamera.Add("office32",pos32);
			
			
			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);
			LookatCamera.Add("office9",lookat9);
			LookatCamera.Add("office10",lookat10);
			LookatCamera.Add("office11",lookat11);
			LookatCamera.Add("office12",lookat12);
			LookatCamera.Add("office13",lookat13);
			LookatCamera.Add("office14",lookat14);
			LookatCamera.Add("office15",lookat15);
			LookatCamera.Add("office16",lookat16);
			LookatCamera.Add("office17",lookat17);
			LookatCamera.Add("office18",lookat18);
			LookatCamera.Add("office19",lookat19);
			LookatCamera.Add("office20",lookat20);
			LookatCamera.Add("office21",lookat21);
			LookatCamera.Add("office22",lookat22);
			LookatCamera.Add("office23",lookat23);
			LookatCamera.Add("office24",lookat24);
			LookatCamera.Add("office25",lookat25);
			LookatCamera.Add("office26",lookat26);
			LookatCamera.Add("office27",lookat27);
			LookatCamera.Add("office28",lookat28);
			LookatCamera.Add("office29",lookat29);
			LookatCamera.Add("office30",lookat30);
			LookatCamera.Add("office31",lookat31);
			LookatCamera.Add("office32",lookat32);

			
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
		}
	}
}

