//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point3_3
	{
		
		static Vector3 evalator = new Vector3 (0.0f, 0.0f, -2.6f);
		static Vector3 start = new Vector3 (0.0f, 0.0f, 0.0f);

		static Vector3 p1 = new Vector3 (-15.79f, 3.1f, 0.0f);
		static Vector3 p2 = new Vector3 (-15.79F, 3.1F, -9.65F);
		static Vector3 p3 = new Vector3 (-27.07F, 3.1F, -0.17F);

		
		static Vector3 o1 = new Vector3 (26.2F, 3.1F, 16.4F);
		static Vector3 o2 = new Vector3 (9.5F, 3.1F, 9.7F);
		static Vector3 o3 = new Vector3 (17.0F, 3.1F, -6.9F);
		static Vector3 o4 = new Vector3 (33.9F, 3.1F, -0.5F);
		static Vector3 o5 = new Vector3 (-11.5F, 3.1F, 6.7F);
		static Vector3 o6 = new Vector3 (-14.8F, 3.1F, 6.7F);
		static Vector3 o7 = new Vector3 (-18.1F, 3.1F, 6.7F);
		static Vector3 o8 = new Vector3 (-21.4F, 3.1F, 6.7F);
		static Vector3 o9 = new Vector3 (-24.7F, 3.1F, 6.7F);
		static Vector3 o10 = new Vector3 (-30.8F, 3.1F, 9.6F);
		static Vector3 o11 = new Vector3 (-33.7F, 3.1F, 4.7F);
		static Vector3 o12 = new Vector3 (-33.7F, 3.1F, 0.9F);
		static Vector3 o13 = new Vector3 (-33.7F, 3.1F, -2.9F);
		static Vector3 o14 = new Vector3 (-33.7F, 3.1F, -6.9F);
		static Vector3 o15 = new Vector3 (-35.9F, 3.1F, -14.1F);
		static Vector3 o16 = new Vector3 (-31.4F, 3.1F, -16.7F);
		static Vector3 o17 = new Vector3 (-28.1F, 3.1F, -16.7F);
		static Vector3 o18 = new Vector3 (-24.7F, 3.1F, -16.7F);
		static Vector3 o19 = new Vector3 (-21.5F, 3.1F, -16.7F);
		static Vector3 o20 = new Vector3 (-18.2F, 3.1F, -16.7F);
		static Vector3 o21 = new Vector3 (-12.0F, 3.1F, -19.4F);
		static Vector3 o22 = new Vector3 (-9.3F, 3.1F, -14.9F);
		static Vector3 o23 = new Vector3 (-9.3F, 3.1F, -11.6F);
		static Vector3 o24 = new Vector3 (-9.3F, 3.1F, -8.2F);
		static Vector3 o25 = new Vector3 (-9.3F, 3.1F, -3.8F);
		static Vector3 o26 = new Vector3 (-6.9F, 3.1F, 5.3F);
		
		static Vector3 f1 = new Vector3 (26.2F, 3.1F, 9.42F);
		static Vector3 f2 = new Vector3 (17.33F, 3.1F, 9.7F);
		static Vector3 f3 = new Vector3 (17.0F, 3.1F, 0.25F);
		static Vector3 f4 = new Vector3 (25.6F, 3.1F, -0.5F);
		static Vector3 f5 = new Vector3 (-11.5F, 3.1F,-0.17F);
		static Vector3 f6 = new Vector3 (-14.8F, 3.1F,-0.17F);
		static Vector3 f7 = new Vector3 (-18.1F, 3.1F,-0.17F);
		static Vector3 f8 = new Vector3 (-21.4F, 3.1F,-0.17F);
		static Vector3 f9 = new Vector3 (-24.7F, 3.1F,-0.17F);
		static Vector3 f10 = new Vector3 (-27.07F, 3.1F, 4.7F);
		static Vector3 f11 = new Vector3 (-27.07F, 3.1F, 4.7F);
		static Vector3 f12 = new Vector3 (-27.07F, 3.1F, 0.9F);
		static Vector3 f13 = new Vector3 (-27.07F, 3.1F, -2.9F);
		static Vector3 f14 = new Vector3 (-27.07F, 3.1F, -6.9F);
		static Vector3 f15 = new Vector3 (-31.4F, 3.1F, -9.65F);
		static Vector3 f16 = new Vector3 (-31.4F, 3.1F, -9.65F);
		static Vector3 f17 = new Vector3 (-28.1F, 3.1F, -9.65F);
		static Vector3 f18 = new Vector3 (-24.7F, 3.1F, -9.65F);
		static Vector3 f19 = new Vector3 (-21.5F, 3.1F, -9.65F);
		static Vector3 f20 = new Vector3 (-18.2F, 3.1F, -9.65F);
		static Vector3 f21 = new Vector3 (-15.79F, 3.1F, -14.9F);
		static Vector3 f22 = new Vector3 (-15.79F, 3.1F, -14.9F);
		static Vector3 f23 = new Vector3 (-15.79F, 3.1F, -11.6F);
		static Vector3 f24 = new Vector3 (-15.79F, 3.1F, -8.2F);
		static Vector3 f25 = new Vector3 (-15.79F, 3.1F, -3.8F);
		static Vector3 f26 = new Vector3 (-6.9F, 3.1F, -0.17F);
		
		
		static Vector3[] office1 = new Vector3[] { evalator, start, f3, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator, start, f3, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator, start, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator, start, f3, f4, o4 };
		
		static Vector3[] office5 = new Vector3[] { evalator, start, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator, start, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator, start, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator, start, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator, start, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator, start, p3, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator, start, p3, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator, start, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator, start, p3, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evalator, start, p3, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator, start, p1, p2, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator, start, p1, p2, f16, o16 };
		static Vector3[] office17 = new Vector3[] { evalator, start, p1, p2, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evalator, start, p1, p2, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evalator, start, p1, p2, f19, o19 };
		static Vector3[] office20 = new Vector3[] { evalator, start, p1, p2, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator, start, p1, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator, start, p1, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evalator, start, p1, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator, start, p1, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator, start, p1, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evalator, start, f26, o26 };

		
		static Vector3 pos1 = new Vector3 (289.0F, 87.5F, 245.7F);
		static Vector3 lookat1 = new Vector3 (289.9F, 6.0F, 191.0F);
		static Vector3 pos2 = new Vector3 (291.1F, 73.4F, 252.0F);
		static Vector3 lookat2 = new Vector3 (291.3F, 1.3F, 190.1F);
		static Vector3 pos3 = new Vector3 (291.9F, 77.9F, 239.7F);
		static Vector3 lookat3 = new Vector3 (292.6F, -4.1F, 186.0F);
		static Vector3 pos4 = new Vector3 (297.1F, 73.6F, 250.5F);
		static Vector3 lookat4 = new Vector3 (294.3F, 5.8F, 187.2F);
		static Vector3 pos5 = new Vector3 (269.4F, 85.1F, 239.9F);
		static Vector3 lookat5 = new Vector3 (278.5F, 3.2F, 188.2F);
		static Vector3 pos6 = new Vector3 (278.2F, 77.8F, 238.5F);
		static Vector3 lookat6 = new Vector3 (286.5F, 0.5F, 188.2F);
		static Vector3 pos7 = new Vector3 (279.0F, 69.4F, 243.7F);
		static Vector3 lookat7 = new Vector3 (288.3F, 7.3F, 188.2F);
		static Vector3 pos8 = new Vector3 (258.1F, 71.7F, 248.2F);
		static Vector3 lookat8 = new Vector3 (287.0F, 5.3F, 188.2F);
		static Vector3 pos9 = new Vector3 (273.0F, 68.6F, 234.0F);
		static Vector3 lookat9 = new Vector3 (287.4F, 10.6F, 188.2F);
		static Vector3 pos10 = new Vector3 (268.1F, 68.0F, 235.4F);
		static Vector3 lookat10 = new Vector3 (286.6F, 8.7F, 189.3F);
		static Vector3 pos11 = new Vector3 (266.8F, 62.7F, 239.9F);
		static Vector3 lookat11 = new Vector3 (282.4F, 10.6F, 188.7F);
		static Vector3 pos12 = new Vector3 (275.0F, 61.0F, 241.3F);
		static Vector3 lookat12 = new Vector3 (289.2F, 10.2F, 187.4F);
		static Vector3 pos13 = new Vector3 (268.4F, 69.5F, 233.9F);
		static Vector3 lookat13 = new Vector3 (281.1F, 4.8F, 186.6F);
		static Vector3 pos14 = new Vector3 (266.2F, 65.7F, 238.3F);
		static Vector3 lookat14 = new Vector3 (285.0F, 6.6F, 185.4F);
		static Vector3 pos15 = new Vector3 (265.4F, 79.5F, 235.1F);
		static Vector3 lookat15 = new Vector3 (281.5F, 3.2F, 183.3F);
		static Vector3 pos16 = new Vector3 (285.8F, 76.7F, 247.8F);
		static Vector3 lookat16 = new Vector3 (289.4F, -5.8F, 182.6F);
		static Vector3 pos17 = new Vector3 (274.3F, 76.0F, 235.3F);
		static Vector3 lookat17 = new Vector3 (289.2F, -0.9F, 182.6F);
		static Vector3 pos18 = new Vector3 (272.0F, 69.1F, 237.4F);
		static Vector3 lookat18 = new Vector3 (288.4F, 9.2F, 182.6F);
		static Vector3 pos19 = new Vector3 (278.6F, 65.4F, 238.6F);
		static Vector3 lookat19 = new Vector3 (288.7F, -2.3F, 182.6F);
		static Vector3 pos20 = new Vector3 (265.9F, 73.8F, 234.7F);
		static Vector3 lookat20 = new Vector3 (289.9F, 1.6F, 182.6F);
		static Vector3 pos21 = new Vector3 (272.9F, 71.0F, 234.8F);
		static Vector3 lookat21 = new Vector3 (290.2F, -1.4F, 182.3F);
		static Vector3 pos22 = new Vector3 (269.1F, 81.6F, 230.8F);
		static Vector3 lookat22 = new Vector3 (283.3F, -5.6F, 183.0F);
		static Vector3 pos23 = new Vector3 (269.7F, 76.8F, 225.1F);
		static Vector3 lookat23 = new Vector3 (287.6F, -0.3F, 183.9F);
		static Vector3 pos24 = new Vector3 (265.0F, 68.8F, 238.9F);
		static Vector3 lookat24 = new Vector3 (289.2F, 2.9F, 184.9F);
		static Vector3 pos25 = new Vector3 (270.8F, 79.7F, 228.8F);
		static Vector3 lookat25 = new Vector3 (289.8F, -0.1F, 186.1F);
		static Vector3 pos26 = new Vector3 (265.5F, 65.3F, 233.0F);
		static Vector3 lookat26 = new Vector3 (290.3F, 8.3F, 188.0F);


		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point3_3 ()
		{
			
			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);
			PositnCamera.Add("office21",pos21);
			PositnCamera.Add("office22",pos22);
			PositnCamera.Add("office23",pos23);
			PositnCamera.Add("office24",pos24);
			PositnCamera.Add("office25",pos25);
			PositnCamera.Add("office26",pos26);
			
			
			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);
			LookatCamera.Add("office9",lookat9);
			LookatCamera.Add("office10",lookat10);
			LookatCamera.Add("office11",lookat11);
			LookatCamera.Add("office12",lookat12);
			LookatCamera.Add("office13",lookat13);
			LookatCamera.Add("office14",lookat14);
			LookatCamera.Add("office15",lookat15);
			LookatCamera.Add("office16",lookat16);
			LookatCamera.Add("office17",lookat17);
			LookatCamera.Add("office18",lookat18);
			LookatCamera.Add("office19",lookat19);
			LookatCamera.Add("office20",lookat20);
			LookatCamera.Add("office21",lookat21);
			LookatCamera.Add("office22",lookat22);
			LookatCamera.Add("office23",lookat23);
			LookatCamera.Add("office24",lookat24);
			LookatCamera.Add("office25",lookat25);
			LookatCamera.Add("office26",lookat26);

			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
		}
	}
}

