//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point6_2
	{

		
		public static Vector3 start1 = new Vector3 (21.9f, 1.0F, 4.6f);
		public static Vector3 evalator1 = new Vector3 (21.9f, 1.0F, 1.21f);
		public static Vector3 start2 = new Vector3 (-21.3f, 1.0F, -5.0f);
		public static Vector3 evalator2 = new Vector3 (-21.3f, 1.0F, -8.39f);

		
		public static Vector3 p1 = new Vector3 (37.51F, 1.0F, 4.6F);
		static Vector3 p2 = new Vector3 (-47.88F, 1.0F, -5.0F);
		static Vector3 p3 = new Vector3 (-37.35F, 1.0F, -5.0F);
		static Vector3 p4 = new Vector3 (-30.7F, 1.0F, -14.45F);


		
		static Vector3 o1 = new Vector3 (51.6F, 1.0F, 21.1F);
		static Vector3 o2 = new Vector3 (45.0F, 1.0F, 21.1F);
		static Vector3 o3 = new Vector3 (31.1F, 1.0F, 14.6F);
		static Vector3 o4 = new Vector3 (28.6F, 1.0F, -0.5F);
		static Vector3 o5 = new Vector3 (33.2F, 1.0F, -2.3F);
		static Vector3 o6 = new Vector3 (36.6F, 1.0F, -2.3F);
		static Vector3 o7 = new Vector3 (39.8F, 1.0F, -2.3F);
		static Vector3 o8 = new Vector3 (43.2F, 1.0F, -2.3F);
		static Vector3 o9 = new Vector3 (46.5F, 1.0F, -2.3F);
		static Vector3 o10 = new Vector3 (52.7F, 1.0F, -5.1F);
		static Vector3 o11 = new Vector3 (55.4F, 1.0F, -0.2F);
		static Vector3 o12 = new Vector3 (55.4F, 1.0F, 3.6F);
		static Vector3 o13 = new Vector3 (55.4F, 1.0F, 7.5F);
		static Vector3 o14 = new Vector3 (55.4F, 1.0F, 11.4F);
		static Vector3 o15 = new Vector3 (57.8F, 1.0F, 18.5F);
		static Vector3 o16 = new Vector3 (10.1F, 1.0F, 11.4F);
		static Vector3 o17 = new Vector3 (6.7F, 1.0F, 11.4F);
		static Vector3 o18 = new Vector3 (3.5F, 1.0F, 11.4F);
		static Vector3 o19 = new Vector3 (0.1F, 1.0F, 11.4F);
		static Vector3 o20 = new Vector3 (-3.2F, 1.0F, 11.4F);
		static Vector3 o21 = new Vector3 (-9.3F, 1.0F, 14.2F);
		static Vector3 o22 = new Vector3 (-12.0F, 1.0F, 9.6F);
		static Vector3 o23 = new Vector3 (-12.0F, 1.0F, 6.3F);
		static Vector3 o24 = new Vector3 (-12.0F, 1.0F, 2.9F);
		static Vector3 o25 = new Vector3 (-12.0F, 1.0F, -1.6F);
		static Vector3 o26 = new Vector3 (-14.4F, 1.0F, -10.3F);
		static Vector3 o27 = new Vector3 (-9.8F, 1.0F, -12.1F);
		static Vector3 o28 = new Vector3 (-6.4F, 1.0F, -12.1F);
		static Vector3 o29 = new Vector3 (-3.2F, 1.0F, -12.1F);
		static Vector3 o30 = new Vector3 (0.2F, 1.0F, -12.1F);
		static Vector3 o31 = new Vector3 (3.5F, 1.0F, -12.1F);
		static Vector3 o32 = new Vector3 (9.7F, 1.0F, -14.9F);
		static Vector3 o33 = new Vector3 (12.4F, 1.0F, -10.0F);
		static Vector3 o34 = new Vector3 (12.4F, 1.0F, -6.2F);
		static Vector3 o35 = new Vector3 (12.4F, 1.0F, -2.3F);
		static Vector3 o36 = new Vector3 (12.4F, 1.0F, 1.6F);
		static Vector3 o37 = new Vector3 (14.6F, 1.0F, 9.7F);
		static Vector3 o38 = new Vector3 (-33.0F, 1.0F, 1.5F);
		static Vector3 o39 = new Vector3 (-36.4F, 1.0F, 1.5F);
		static Vector3 o40 = new Vector3 (-39.6F, 1.0F, 1.5F);
		static Vector3 o41 = new Vector3 (-43.0F, 1.0F, 1.5F);
		static Vector3 o42 = new Vector3 (-46.3F, 1.0F, 1.5F);
		static Vector3 o43 = new Vector3 (-52.4F, 1.0F, 4.4F);
		static Vector3 o44 = new Vector3 (-55.1F, 1.0F, -0.3F);
		static Vector3 o45 = new Vector3 (-55.1F, 1.0F, -4.1F);
		static Vector3 o46 = new Vector3 (-55.1F, 1.0F, -8.0F);
		static Vector3 o47 = new Vector3 (-55.2F, 1.0F, -12.0F);
		static Vector3 o48 = new Vector3 (-57.5F, 1.0F, -19.1F);
		static Vector3 o49 = new Vector3 (-52.9F, 1.0F, -22.0F);
		static Vector3 o50 = new Vector3 (-49.5F, 1.0F, -22.0F);
		static Vector3 o51 = new Vector3 (-46.3F, 1.0F, -22.0F);
		static Vector3 o52 = new Vector3 (-42.9F, 1.0F, -22.0F);
		static Vector3 o53 = new Vector3 (-39.6F, 1.0F, -22.0F);
		static Vector3 o54 = new Vector3 (-33.4F, 1.0F, -24.8F);
		static Vector3 o55 = new Vector3 (-30.7F, 1.0F, -19.8F);
		static Vector3 o56 = new Vector3 (-30.7F, 1.0F, -16.5F);
		static Vector3 o57 = new Vector3 (-30.7F, 1.0F, -13.3F);
		static Vector3 o58 = new Vector3 (-30.7F, 1.0F, -8.8F);
		static Vector3 o59 = new Vector3 (-28.5F, 1.0F, -0.4F);

		
		static Vector3 f1 = new Vector3 (51.6F, 1.0F, 13.72F);
		static Vector3 f2 = new Vector3 (45.0F, 1.0F, 13.72F);
		static Vector3 f3 = new Vector3 (37.44F, 1.0F, 13.77F);
		static Vector3 f4 = new Vector3 (28.6F, 1.0F, 4.6F);
		static Vector3 f5 = new Vector3 (33.2F, 1.0F, 4.6F);
		static Vector3 f6 = new Vector3 (36.6F, 1.0F, 4.6F);
		static Vector3 f7 = new Vector3 (39.8F, 1.0F, 4.6F);
		static Vector3 f8 = new Vector3 (43.2F, 1.0F, 4.6F);
		static Vector3 f9 = new Vector3 (46.5F, 1.0F, 4.6F);
		static Vector3 f10 = new Vector3 (48.82F, 1.0F, -0.2F);
		static Vector3 f11 = new Vector3 (48.82F, 1.0F, -0.2F);
		static Vector3 f12 = new Vector3 (48.82F, 1.0F, 3.6F);
		static Vector3 f13 = new Vector3 (48.82F, 1.0F, 7.5F);
		static Vector3 f14 = new Vector3 (48.82F, 1.0F, 11.4F);
		static Vector3 f15 = new Vector3 (51.6F, 1.0F, 13.72F);
		static Vector3 f16 = new Vector3 (10.1F, 1.0F, 4.6F);
		static Vector3 f17 = new Vector3 (6.7F, 1.0F, 4.6F);
		static Vector3 f18 = new Vector3 (3.5F, 1.0F, 4.6F);
		static Vector3 f19 = new Vector3 (0.1F, 1.0F, 4.6F);
		static Vector3 f20 = new Vector3 (-3.2F, 1.0F, 4.6F);
		static Vector3 f21 = new Vector3 (-5.6F, 1.0F, 9.6F);
		static Vector3 f22 = new Vector3 (-5.6F, 1.0F, 9.6F);
		static Vector3 f23 = new Vector3 (-5.6F, 1.0F, 6.3F);
		static Vector3 f24 = new Vector3 (-5.6F, 1.0F, 2.9F);
		static Vector3 f25 = new Vector3 (-5.6F, 1.0F, -1.6F);
		static Vector3 f26 = new Vector3 (-14.4F, 1.0F, -5.0F);
		static Vector3 f27 = new Vector3 (-9.8F, 1.0F, -5.0F);
		static Vector3 f28 = new Vector3 (-6.4F, 1.0F, -5.0F);
		static Vector3 f29 = new Vector3 (-3.2F, 1.0F, -5.0F);
		static Vector3 f30 = new Vector3 (0.2F, 1.0F, -5.0F);
		static Vector3 f31 = new Vector3 (3.5F, 1.0F, -5.0F);
		static Vector3 f32 = new Vector3 (5.81F, 1.0F, -10.0F);
		static Vector3 f33 = new Vector3 (5.81F, 1.0F, -10.0F);
		static Vector3 f34 = new Vector3 (5.81F, 1.0F, -6.2F);
		static Vector3 f35 = new Vector3 (5.81F, 1.0F, -2.3F);
		static Vector3 f36 = new Vector3 (5.81F, 1.0F, 1.6F);
		static Vector3 f37 = new Vector3 (14.6F, 1.0F, 4.6F);
		static Vector3 f38 = new Vector3 (-33.0F, 1.0F, -5.0F);
		static Vector3 f39 = new Vector3 (-36.4F, 1.0F, -5.0F);
		static Vector3 f40 = new Vector3 (-39.6F, 1.0F, -5.0F);
		static Vector3 f41 = new Vector3 (-43.0F, 1.0F, -5.0F);
		static Vector3 f42 = new Vector3 (-46.3F, 1.0F, -5.0F);
		static Vector3 f43 = new Vector3 (-48.45F, 1.0F, -0.3F);
		static Vector3 f44 = new Vector3 (-48.45F, 1.0F, -0.3F);
		static Vector3 f45 = new Vector3 (-48.45F, 1.0F, -4.1F);
		static Vector3 f46 = new Vector3 (-48.45F, 1.0F, -8.0F);
		static Vector3 f47 = new Vector3 (-48.45F, 1.0F, -12.0F);
		static Vector3 f48 = new Vector3 (-52.9F, 1.0F, -14.45F);
		static Vector3 f49 = new Vector3 (-52.9F, 1.0F, -14.45F);
		static Vector3 f50 = new Vector3 (-49.5F, 1.0F, -14.45F);
		static Vector3 f51 = new Vector3 (-46.3F, 1.0F, -14.45F);
		static Vector3 f52 = new Vector3 (-42.9F, 1.0F, -14.45F);
		static Vector3 f53 = new Vector3 (-39.6F, 1.0F, -14.45F);
		static Vector3 f54 = new Vector3 (-37.35F, 1.0F, -19.8F);
		static Vector3 f55 = new Vector3 (-37.35F, 1.0F, -19.8F);
		static Vector3 f56 = new Vector3 (-37.35F, 1.0F, -16.5F);
		static Vector3 f57 = new Vector3 (-37.35F, 1.0F, -13.3F);
		static Vector3 f58 = new Vector3 (-37.35F, 1.0F, -8.8F);
		static Vector3 f59 = new Vector3 (-28.5F, 1.0F, -5.0F);

		
		static Vector3[] office1 = new Vector3[] { evalator1, start1, p1, f3, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, start1, p1, f3, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, start1, p1, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator1, start1, f4, o4 };
		static Vector3[] office5 = new Vector3[] { evalator1, start1, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator1, start1, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator1, start1, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator1, start1, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator1, start1, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator1, start1, f12, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator1, start1, f12,f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator1, start1, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator1, start1, f12, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evalator1, start1, f12, f14, o14 };

		static Vector3[] office15 = new Vector3[] { evalator1, start1, p1, f3, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator1, start1, f16, o16 };
		static Vector3[] office17 = new Vector3[] { evalator1, start1, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evalator1, start1, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evalator1, start1, f19, o19 };
		static Vector3[] office20 = new Vector3[] { evalator2, start2, f28, f24, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator2, start2, f28, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator2, start2, f28, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evalator2, start2, f28, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator2, start2, f28, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator2, start2, f28, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evalator2, start2, f26, o26 };
		static Vector3[] office27 = new Vector3[] { evalator2, start2, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator2, start2, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator1, start1, f17, f34, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator1, start1, f17, f34, f30, o30 };
		
		static Vector3[] office31 = new Vector3[] { evalator1, start1, f17, f34, f31, o31 };
		static Vector3[] office32 = new Vector3[] { evalator1, start1, f17, f32, o32 };
		
		static Vector3[] office33 = new Vector3[] { evalator1, start1, f17,  f33, o33 };
		static Vector3[] office34 = new Vector3[] { evalator1, start1, f17, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evalator1, start1, f17, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evalator1, start1, f17, f36, o36 };
		
		static Vector3[] office37 = new Vector3[] { evalator1, start1, f37, o37 };
		static Vector3[] office38 = new Vector3[] { evalator2, start2, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evalator2, start2, f39, o39 };
		static Vector3[] office40 = new Vector3[] { evalator2, start2, f40, o40 };
		
		static Vector3[] office41 = new Vector3[] { evalator2, start2, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evalator2, start2, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evalator2, start2, p2, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evalator2, start2, p2, f44, o44 };
		static Vector3[] office45 = new Vector3[] { evalator2, start2, p2, f45, o45 };
		static Vector3[] office46 = new Vector3[] { evalator2, start2, p2, f46, o46 };
		static Vector3[] office47 = new Vector3[] { evalator2, start2, p2, f47, o47 };
		static Vector3[] office48 = new Vector3[] { evalator2, start2, p3, p4, f48, o48 };
		
		static Vector3[] office49 = new Vector3[] { evalator2, start2, p3, p4, f49, o49 };
		static Vector3[] office50 = new Vector3[] { evalator2, start2, p3, p4, f50, o50 };
		static Vector3[] office51 = new Vector3[] { evalator2, start2, p3, p4, f51, o51 };
		static Vector3[] office52 = new Vector3[] { evalator2, start2, p3, p4, f52, o52 };
		static Vector3[] office53 = new Vector3[] { evalator2, start2, p3, p4, f53, o53 };
		static Vector3[] office54 = new Vector3[] { evalator2, start2, p3, f54, o54 };		
		static Vector3[] office55 = new Vector3[] { evalator2, start2, p3, f55, o55 };		
		
		static Vector3[] office56 = new Vector3[] { evalator2, start2, p3, f56, o56 };	
		static Vector3[] office57 = new Vector3[] { evalator2, start2, p3, f57, o57 };	
		static Vector3[] office58 = new Vector3[] { evalator2, start2, p3, f58, o58 };
		static Vector3[] office59 = new Vector3[] { evalator2, start2, f59, o59 };

		
		static Vector3 pos1 = new Vector3 (335.0F, 72.8F, 261.5F);
		static Vector3 lookat1 = new Vector3 (315.6F, 9.1F, 203.2F);
		static Vector3 pos2 = new Vector3 (341.6F, 83.0F, 258.6F);
		static Vector3 lookat2 = new Vector3 (323.4F, 16.1F, 202.3F);
		static Vector3 pos3 = new Vector3 (336.1F, 87.4F, 249.9F);
		static Vector3 lookat3 = new Vector3 (326.4F, 16.1F, 201.4F);
		static Vector3 pos4 = new Vector3 (337.0F, 82.4F, 273.4F);
		static Vector3 lookat4 = new Vector3 (317.2F, 3.8F, 197.9F);
		static Vector3 pos5 = new Vector3 (324.3F, 91.1F, 245.8F);
		static Vector3 lookat5 = new Vector3 (321.5F, 13.2F, 197.7F);
		static Vector3 pos6 = new Vector3 (355.4F, 74.1F, 257.6F);
		static Vector3 lookat6 = new Vector3 (333.0F, 10.1F, 197.7F);
		static Vector3 pos7 = new Vector3 (354.6F, 74.7F, 255.0F);
		static Vector3 lookat7 = new Vector3 (333.7F, 7.3F, 197.7F);
		static Vector3 pos8 = new Vector3 (359.2F, 80.9F, 249.6F);
		static Vector3 lookat8 = new Vector3 (333.1F, 7.9F, 197.7F);
		static Vector3 pos9 = new Vector3 (351.4F, 77.3F, 258.2F);
		static Vector3 lookat9 = new Vector3 (331.0F, 11.3F, 197.7F);
		static Vector3 pos10 = new Vector3 (362.2F, 88.8F, 248.8F);
		static Vector3 lookat10 = new Vector3 (333.6F, 15.8F, 196.5F);
		static Vector3 pos11 = new Vector3 (357.9F, 81.5F, 260.3F);
		static Vector3 lookat11 = new Vector3 (330.9F, 14.2F, 197.3F);
		static Vector3 pos12 = new Vector3 (347.7F, 82.9F, 253.9F);
		static Vector3 lookat12 = new Vector3 (321.0F, 9.8F, 198.4F);
		static Vector3 pos13 = new Vector3 (343.4F, 91.0F, 256.3F);
		static Vector3 lookat13 = new Vector3 (327.3F, 17.3F, 199.5F);
		static Vector3 pos14 = new Vector3 (367.6F, 103.6F, 244.9F);
		static Vector3 lookat14 = new Vector3 (335.0F, 23.8F, 200.6F);
		static Vector3 pos16 = new Vector3 (286.5F, 93.5F, 242.6F);
		static Vector3 lookat16 = new Vector3 (286.0F, 12.7F, 196.0F);
		static Vector3 pos17 = new Vector3 (287.7F, 99.2F, 246.4F);
		static Vector3 lookat17 = new Vector3 (289.2F, 19.7F, 196.0F);
		static Vector3 pos18 = new Vector3 (290.1F, 85.7F, 252.0F);
		static Vector3 lookat18 = new Vector3 (291.4F, 16.4F, 196.0F);
		static Vector3 pos19 = new Vector3 (282.4F, 82.6F, 245.0F);
		static Vector3 lookat19 = new Vector3 (286.5F, 12.7F, 196.0F);
		static Vector3 pos20 = new Vector3 (283.7F, 86.6F, 246.7F);
		static Vector3 lookat20 = new Vector3 (284.7F, 11.8F, 196.0F);
		static Vector3 pos21 = new Vector3 (285.8F, 72.3F, 253.7F);
		static Vector3 lookat21 = new Vector3 (289.5F, 14.6F, 196.2F);
		static Vector3 pos22 = new Vector3 (286.1F, 101.3F, 245.0F);
		static Vector3 lookat22 = new Vector3 (288.9F, 16.3F, 196.3F);
		static Vector3 pos23 = new Vector3 (286.7F, 84.5F, 257.0F);
		static Vector3 lookat23 = new Vector3 (288.4F, 11.9F, 195.6F);
		static Vector3 pos24 = new Vector3 (280.9F, 80.1F, 251.6F);
		static Vector3 lookat24 = new Vector3 (284.5F, 14.2F, 194.8F);
		static Vector3 pos25 = new Vector3 (289.7F, 81.1F, 253.8F);
		static Vector3 lookat25 = new Vector3 (293.3F, 11.7F, 193.8F);
		static Vector3 pos26 = new Vector3 (278.3F, 74.6F, 249.3F);
		static Vector3 lookat26 = new Vector3 (284.9F, 11.6F, 192.5F);
		static Vector3 pos27 = new Vector3 (294.2F, 81.5F, 249.7F);
		static Vector3 lookat27 = new Vector3 (294.1F, 10.6F, 192.3F);
		static Vector3 pos28 = new Vector3 (291.1F, 75.8F, 252.6F);
		static Vector3 lookat28 = new Vector3 (291.3F, 11.0F, 192.3F);
		static Vector3 pos29 = new Vector3 (284.1F, 92.3F, 248.2F);
		static Vector3 lookat29 = new Vector3 (286.8F, 8.8F, 192.3F);
		static Vector3 pos30 = new Vector3 (285.2F, 84.7F, 252.2F);
		static Vector3 lookat30 = new Vector3 (288.9F, 12.7F, 192.3F);
		static Vector3 pos31 = new Vector3 (286.5F, 86.6F, 244.5F);
		static Vector3 lookat31 = new Vector3 (287.3F, 11.9F, 192.3F);
		static Vector3 pos32 = new Vector3 (283.6F, 85.9F, 244.7F);
		static Vector3 lookat32 = new Vector3 (289.4F, 10.9F, 190.9F);
		static Vector3 pos33 = new Vector3 (283.3F, 86.6F, 253.5F);
		static Vector3 lookat33 = new Vector3 (286.8F, 9.3F, 192.0F);
		static Vector3 pos34 = new Vector3 (282.1F, 82.0F, 244.4F);
		static Vector3 lookat34 = new Vector3 (289.0F, 12.7F, 192.8F);
		static Vector3 pos35 = new Vector3 (284.8F, 89.1F, 239.8F);
		static Vector3 lookat35 = new Vector3 (287.2F, 2.2F, 193.7F);
		static Vector3 pos36 = new Vector3 (285.7F, 77.7F, 238.6F);
		static Vector3 lookat36 = new Vector3 (287.3F, 8.9F, 194.5F);
		static Vector3 pos37 = new Vector3 (294.9F, 88.1F, 241.6F);
		static Vector3 lookat37 = new Vector3 (297.6F, 17.3F, 195.8F);
		static Vector3 pos38 = new Vector3 (240.1F, 77.5F, 239.1F);
		static Vector3 lookat38 = new Vector3 (271.5F, 9.7F, 190.1F);
		static Vector3 pos39 = new Vector3 (252.4F, 82.0F, 231.8F);
		static Vector3 lookat39 = new Vector3 (277.6F, 9.7F, 190.1F);
		static Vector3 pos40 = new Vector3 (249.7F, 77.3F, 238.4F);
		static Vector3 lookat40 = new Vector3 (280.0F, 7.2F, 190.1F);
		static Vector3 pos41 = new Vector3 (261.6F, 91.0F, 239.3F);
		static Vector3 lookat41 = new Vector3 (283.2F, 9.7F, 190.1F);
		static Vector3 pos42 = new Vector3 (257.4F, 84.9F, 232.5F);
		static Vector3 lookat42 = new Vector3 (276.2F, 9.7F, 190.1F);
		static Vector3 pos43 = new Vector3 (256.8F, 99.4F, 230.3F);
		static Vector3 lookat43 = new Vector3 (273.7F, 6.5F, 189.9F);
		static Vector3 pos44 = new Vector3 (245.0F, 85.4F, 235.9F);
		static Vector3 lookat44 = new Vector3 (267.9F, 9.7F, 190.3F);
		static Vector3 pos45 = new Vector3 (258.4F, 78.4F, 237.0F);
		static Vector3 lookat45 = new Vector3 (276.0F, 7.5F, 189.7F);
		static Vector3 pos46 = new Vector3 (243.9F, 82.0F, 242.5F);
		static Vector3 lookat46 = new Vector3 (277.2F, 9.7F, 189.1F);
		static Vector3 pos47 = new Vector3 (252.4F, 80.7F, 232.2F);
		static Vector3 lookat47 = new Vector3 (275.1F, 8.5F, 188.4F);
		static Vector3 pos48 = new Vector3 (264.4F, 91.2F, 226.3F);
		static Vector3 lookat48 = new Vector3 (273.0F, 9.7F, 187.6F);
		static Vector3 pos49 = new Vector3 (258.5F, 91.4F, 227.5F);
		static Vector3 lookat49 = new Vector3 (273.4F, 6.9F, 187.3F);
		static Vector3 pos50 = new Vector3 (253.6F, 68.1F, 247.5F);
		static Vector3 lookat50 = new Vector3 (277.6F, 9.7F, 187.3F);
		static Vector3 pos51 = new Vector3 (258.6F, 84.0F, 239.3F);
		static Vector3 lookat51 = new Vector3 (273.8F, 0.2F, 187.3F);
		static Vector3 pos52 = new Vector3 (258.8F, 79.7F, 233.1F);
		static Vector3 lookat52 = new Vector3 (274.7F, -0.2F, 187.3F);
		static Vector3 pos53 = new Vector3 (260.0F, 65.2F, 238.2F);
		static Vector3 lookat53 = new Vector3 (277.6F, 1.8F, 187.3F);
		static Vector3 pos54 = new Vector3 (249.4F, 81.4F, 240.4F);
		static Vector3 lookat54 = new Vector3 (274.0F, 9.9F, 185.7F);
		static Vector3 pos55 = new Vector3 (256.7F, 71.5F, 235.3F);
		static Vector3 lookat55 = new Vector3 (280.1F, 9.7F, 187.1F);
		static Vector3 pos56 = new Vector3 (263.6F, 72.0F, 232.9F);
		static Vector3 lookat56 = new Vector3 (276.8F, 3.9F, 187.6F);
		static Vector3 pos57 = new Vector3 (252.5F, 69.8F, 235.9F);
		static Vector3 lookat57 = new Vector3 (275.0F, 8.3F, 188.2F);
		static Vector3 pos58 = new Vector3 (252.7F, 65.4F, 232.1F);
		static Vector3 lookat58 = new Vector3 (272.2F, 11.5F, 188.9F);
		static Vector3 pos59 = new Vector3 (252.7F, 71.3F, 230.0F);
		static Vector3 lookat59 = new Vector3 (270.9F, 20.9F, 189.9F);
		static Vector3 pos15 = new Vector3 (352.2F, 83.3F, 261.5F);
		static Vector3 lookat15 = new Vector3 (328.0F, 13.2F, 201.9F);

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();
		public Point6_2 ()
		{
			
			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);
			LookatCamera.Add("office9",lookat9);
			LookatCamera.Add("office10",lookat10);
			LookatCamera.Add("office11",lookat11);
			LookatCamera.Add("office12",lookat12);
			LookatCamera.Add("office13",lookat13);
			LookatCamera.Add("office14",lookat14);
			LookatCamera.Add("office15",lookat15);
			LookatCamera.Add("office16",lookat16);
			LookatCamera.Add("office17",lookat17);
			LookatCamera.Add("office18",lookat18);
			LookatCamera.Add("office19",lookat19);
			LookatCamera.Add("office20",lookat20);
			LookatCamera.Add("office21",lookat21);
			LookatCamera.Add("office22",lookat22);
			LookatCamera.Add("office23",lookat23);
			LookatCamera.Add("office24",lookat24);
			LookatCamera.Add("office25",lookat25);
			LookatCamera.Add("office26",lookat26);
			LookatCamera.Add("office27",lookat27);
			LookatCamera.Add("office28",lookat28);
			LookatCamera.Add("office29",lookat29);
			LookatCamera.Add("office30",lookat30);
			LookatCamera.Add("office31",lookat31);
			LookatCamera.Add("office32",lookat32);
			LookatCamera.Add("office33",lookat33);
			LookatCamera.Add("office34",lookat34);
			LookatCamera.Add("office35",lookat35);
			LookatCamera.Add("office36",lookat36);
			LookatCamera.Add("office37",lookat37);
			LookatCamera.Add("office38",lookat38);
			LookatCamera.Add("office39",lookat39);
			LookatCamera.Add("office40",lookat40);
			LookatCamera.Add("office41",lookat41);
			LookatCamera.Add("office42",lookat42);
			LookatCamera.Add("office43",lookat43);
			LookatCamera.Add("office44",lookat44);
			LookatCamera.Add("office45",lookat45);
			LookatCamera.Add("office46",lookat46);
			LookatCamera.Add("office47",lookat47);
			LookatCamera.Add("office48",lookat48);
			LookatCamera.Add("office49",lookat49);
			LookatCamera.Add("office50",lookat50);
			LookatCamera.Add("office51",lookat51);
			LookatCamera.Add("office52",lookat52);
			LookatCamera.Add("office53",lookat53);
			LookatCamera.Add("office54",lookat54);
			LookatCamera.Add("office55",lookat55);
			LookatCamera.Add("office56",lookat56);
			LookatCamera.Add("office57",lookat57);
			LookatCamera.Add("office58",lookat58);
			LookatCamera.Add("office59",lookat59);

			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);
			PositnCamera.Add("office21",pos21);
			PositnCamera.Add("office22",pos22);
			PositnCamera.Add("office23",pos23);
			PositnCamera.Add("office24",pos24);
			PositnCamera.Add("office25",pos25);
			PositnCamera.Add("office26",pos26);
			PositnCamera.Add("office27",pos27);
			PositnCamera.Add("office28",pos28);
			PositnCamera.Add("office29",pos29);
			PositnCamera.Add("office30",pos30);
			PositnCamera.Add("office31",pos31);
			PositnCamera.Add("office32",pos32);
			PositnCamera.Add("office33",pos33);
			PositnCamera.Add("office34",pos34);
			PositnCamera.Add("office35",pos35);
			PositnCamera.Add("office36",pos36);
			PositnCamera.Add("office37",pos37);
			PositnCamera.Add("office38",pos38);
			PositnCamera.Add("office39",pos39);
			PositnCamera.Add("office40",pos40);
			PositnCamera.Add("office41",pos41);
			PositnCamera.Add("office42",pos42);
			PositnCamera.Add("office43",pos43);
			PositnCamera.Add("office44",pos44);
			PositnCamera.Add("office45",pos45);
			PositnCamera.Add("office46",pos46);
			PositnCamera.Add("office47",pos47);
			PositnCamera.Add("office48",pos48);
			PositnCamera.Add("office49",pos49);
			PositnCamera.Add("office50",pos50);
			PositnCamera.Add("office51",pos51);
			PositnCamera.Add("office52",pos52);
			PositnCamera.Add("office53",pos53);
			PositnCamera.Add("office54",pos54);
			PositnCamera.Add("office55",pos55);
			PositnCamera.Add("office56",pos56);
			PositnCamera.Add("office57",pos57);
			PositnCamera.Add("office58",pos58);
			PositnCamera.Add("office59",pos59);


			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
			dictionary.Add("office45",office45);
			dictionary.Add("office46",office46);
			dictionary.Add("office47",office47);
			dictionary.Add("office48",office48);
			dictionary.Add("office49",office49);
			dictionary.Add("office50",office50);
			dictionary.Add("office51",office51);
			dictionary.Add("office52",office52);
			dictionary.Add("office53",office53);
			dictionary.Add("office54",office54);
			dictionary.Add("office55",office55);
			dictionary.Add("office56",office56);
			dictionary.Add("office57",office57);
			dictionary.Add("office58",office58);
			dictionary.Add("office59",office59);
		}
	}
}

