//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point3_2handicap
	{
		public static Vector3 evalator1 = new Vector3 (21.79f, 1.5f, 4.18f);
		public static Vector3 evalator2 = new Vector3 (-20.63f, 1.5f, -5.13f);

		static Vector3 o1 = new Vector3 (31.5F, 3.1F, 16.6F);
		static Vector3 o2 = new Vector3 (28.2F, 3.1F, 16.6F);
		static Vector3 o3 = new Vector3 (25.0F, 3.1F, 16.6F);
		static Vector3 o4 = new Vector3 (21.7F, 3.1F, 16.6F);
		static Vector3 o5 = new Vector3 (18.3F, 3.1F, 16.6F);
		static Vector3 o6 = new Vector3 (12.2F, 3.1F, 19.4F);
		static Vector3 o7 = new Vector3 (9.4F, 3.1F, 14.9F);
		static Vector3 o8 = new Vector3 (9.4F, 3.1F, 11.5F);
		static Vector3 o9 = new Vector3 (9.4F, 3.1F, 8.2F);
		static Vector3 o10 = new Vector3 (9.4F, 3.1F, 3.8F);
		static Vector3 o11 = new Vector3 (7.1F, 3.1F, -5.2F);
		static Vector3 o12 = new Vector3 (11.7F, 3.1F, -6.8F);
		static Vector3 o13 = new Vector3 (15.0F, 3.1F, -6.8F);
		static Vector3 o14 = new Vector3 (18.3F, 3.1F, -6.8F);
		static Vector3 o15 = new Vector3 (21.6F, 3.1F, -6.8F);
		static Vector3 o16 = new Vector3 (24.9F, 3.1F, -6.8F);
		static Vector3 o17 = new Vector3 (31.1F, 3.1F, -9.6F);
		static Vector3 o18 = new Vector3 (33.8F, 3.1F, -4.8F);
		static Vector3 o19 = new Vector3 (33.8F, 3.1F, -0.9F);
		static Vector3 o20 = new Vector3 (33.8F, 3.1F, 2.9F);
		static Vector3 o21 = new Vector3 (33.8F, 3.1F, 6.9F);
		static Vector3 o22 = new Vector3 (36.1F, 3.1F, 13.9F);
		static Vector3 o23 = new Vector3 (-11.6F, 3.1F, 6.8F);
		static Vector3 o24 = new Vector3 (-14.9F, 3.1F, 6.8F);
		static Vector3 o25 = new Vector3 (-18.2F, 3.1F, 6.8F);
		static Vector3 o26 = new Vector3 (-21.4F, 3.1F, 6.8F);
		static Vector3 o27 = new Vector3 (-24.8F, 3.1F, 6.8F);
		static Vector3 o28 = new Vector3 (-30.9F, 3.1F, 9.6F);
		static Vector3 o29 = new Vector3 (-33.7F, 3.1F, 5.0F);
		static Vector3 o30 = new Vector3 (-33.7F, 3.1F, 1.7F);
		static Vector3 o31 = new Vector3 (-33.7F, 3.1F, -1.6F);
		static Vector3 o32 = new Vector3 (-33.7F, 3.1F, -6.1F);
		static Vector3 o33 = new Vector3 (-36.1F, 3.1F, -13.9F);
		static Vector3 o34 = new Vector3 (-31.4F, 3.1F, -16.6F);
		static Vector3 o35 = new Vector3 (-28.1F, 3.1F, -16.6F);
		static Vector3 o36 = new Vector3 (-24.8F, 3.1F, -16.6F);
		static Vector3 o37 = new Vector3 (-21.5F, 3.1F, -16.6F);
		static Vector3 o38 = new Vector3 (-18.2F, 3.1F, -16.6F);
		static Vector3 o39 = new Vector3 (-12.0F, 3.1F, -19.5F);
		static Vector3 o40 = new Vector3 (-9.3F, 3.1F, -14.7F);
		static Vector3 o41 = new Vector3 (-9.3F, 3.1F, -11.4F);
		static Vector3 o42 = new Vector3 (-9.2F, 3.1F, -8.1F);
		static Vector3 o43 = new Vector3 (-9.3F, 3.1F, -3.6F);
		static Vector3 o44 = new Vector3 (-7.0F, 3.1F, 5.2F);
		
		static Vector3 f1 = new Vector3 (31.5F, 3.1F, 9.54F);
		static Vector3 f2 = new Vector3 (28.2F, 3.1F, 9.54F);
		static Vector3 f3 = new Vector3 (25.0F, 3.1F, 9.54F);
		static Vector3 f4 = new Vector3 (21.7F, 3.1F, 9.54F);
		static Vector3 f5 = new Vector3 (18.3F, 3.1F, 9.54F);
		static Vector3 f6 = new Vector3 (15.91F, 3.1F, 14.9F);
		static Vector3 f7 = new Vector3 (15.91F, 3.1F, 14.9F);
		static Vector3 f8 = new Vector3 (15.91F, 3.1F, 11.5F);
		static Vector3 f9 = new Vector3 (15.91F, 3.1F, 8.2F);
		static Vector3 f10 = new Vector3 (15.91F, 3.1F, 3.8F);
		static Vector3 f11 = new Vector3 (7.1F, 3.1F, -0.01F);
		static Vector3 f12 = new Vector3 (11.7F, 3.1F, -0.01F);
		static Vector3 f13 = new Vector3 (15.0F, 3.1F, -0.01F);
		static Vector3 f14 = new Vector3 (18.3F, 3.1F, -0.01F);
		static Vector3 f15 = new Vector3 (21.6F, 3.1F, -0.01F);
		static Vector3 f16 = new Vector3 (24.9F, 3.1F, -0.01F);
		static Vector3 f17 = new Vector3 (27.59F, 3.1F, -4.8F);
		static Vector3 f18 = new Vector3 (27.59F, 3.1F, -4.8F);
		static Vector3 f19 = new Vector3 (27.59F, 3.1F, -0.9F);
		static Vector3 f20 = new Vector3 (27.59F, 3.1F, 2.9F);
		static Vector3 f21 = new Vector3 (27.59F, 3.1F, 6.9F);
		static Vector3 f22 = new Vector3 (31.5F, 3.1F, 9.54F);
		static Vector3 f23 = new Vector3 (-11.6F, 3.1F, 0.09F);
		static Vector3 f24 = new Vector3 (-14.9F, 3.1F, 0.09F);
		static Vector3 f25 = new Vector3 (-18.2F, 3.1F, 0.09F);
		static Vector3 f26 = new Vector3 (-21.4F, 3.1F, 0.09F);
		static Vector3 f27 = new Vector3 (-24.8F, 3.1F, 0.09F);
		static Vector3 f28 = new Vector3 (-27.09F, 3.1F, 5.0F);
		static Vector3 f29 = new Vector3 (-27.09F, 3.1F, 5.0F);
		static Vector3 f30 = new Vector3 (-27.09F, 3.1F, 1.7F);
		static Vector3 f31 = new Vector3 (-27.09F, 3.1F, -1.6F);
		static Vector3 f32 = new Vector3 (-27.09F, 3.1F, -6.1F);
		static Vector3 f33 = new Vector3 (-31.4F, 3.1F, -9.93F);
		static Vector3 f34 = new Vector3 (-31.4F, 3.1F, -9.93F);
		static Vector3 f35 = new Vector3 (-28.1F, 3.1F, -9.93F);
		static Vector3 f36 = new Vector3 (-24.8F, 3.1F, -9.93F);
		static Vector3 f37 = new Vector3 (-21.5F, 3.1F, -9.93F);
		static Vector3 f38 = new Vector3 (-18.2F, 3.1F, -9.93F);
		static Vector3 f39 = new Vector3 (-15.45F, 3.1F, -14.7F);
		static Vector3 f40 = new Vector3 (-15.45F, 3.1F, -14.7F);
		static Vector3 f41 = new Vector3 (-15.45F, 3.1F, -11.4F);
		static Vector3 f42 = new Vector3 (-15.45F, 3.1F, -8.1F);
		static Vector3 f43 = new Vector3 (-15.45F, 3.1F, -3.6F);
		static Vector3 f44 = new Vector3 (-7.0F, 3.1F, 0.09F);

		static Vector3[] office1 = new Vector3[] { evalator1, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, f3, o3 };		
		static Vector3[] office4 = new Vector3[] { evalator1, f4, o4 };		
		static Vector3[] office5 = new Vector3[] { evalator1, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator1, f9, f6, o6 };		
		static Vector3[] office7 = new Vector3[] { evalator1, f7, o7 };		
		static Vector3[] office8 = new Vector3[] { evalator1, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator1, f9, o9 };		
		static Vector3[] office10 = new Vector3[] { evalator1, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator1, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator1, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator1, f13, o13 };		
		static Vector3[] office14 = new Vector3[] { evalator1, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator1, f15, o15 };		
		static Vector3[] office16 = new Vector3[] { evalator1, f16, o16 };		
		static Vector3[] office17 = new Vector3[] { evalator1, f20, f17, o17 };		
		static Vector3[] office18 = new Vector3[] { evalator1, f18, o18 };		
		static Vector3[] office19 = new Vector3[] { evalator1, f19, o19 };		
		static Vector3[] office20 = new Vector3[] { evalator1, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator1, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator1, f4, f22, o22 };	

		static Vector3[] office23 = new Vector3[] { evalator2, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator2, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator2, f25, o25 };		
		static Vector3[] office26 = new Vector3[] { evalator2, f26, o26 };		
		static Vector3[] office27 = new Vector3[] { evalator2, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator2, f31, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator2, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator2, f30, o30 };		
		static Vector3[] office31 = new Vector3[] { evalator2, f31, o31 };		
		static Vector3[] office32 = new Vector3[] { evalator2, f32, o32 };		
		static Vector3[] office33 = new Vector3[] { evalator2, f36, f33, o33 };
		static Vector3[] office34 = new Vector3[] { evalator2, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evalator2, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evalator2, f36, o36 };		
		static Vector3[] office37 = new Vector3[] { evalator2, f37, o37 };		
		static Vector3[] office38 = new Vector3[] { evalator2, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evalator2, f42, f39, o39 };		
		static Vector3[] office40 = new Vector3[] { evalator2, f40, o40 };		
		static Vector3[] office41 = new Vector3[] { evalator2, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evalator2, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evalator2, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evalator2, f44, o44 };
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();

		public Point3_2handicap ()
		{
			
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
		}
	}
}

