//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point6_1
	{
		static Vector3 start1 = new Vector3 (32.64f, 1.0f, 8.89f);//
		static Vector3 start2 = new Vector3 (13.24f, 1.0f, 8.89f);//
		static Vector3 start3 = new Vector3 (-31.97f, 1.0f, -9.37999f);//

		static Vector3 p0 = new Vector3 (32.64f, 1.0f, 4.7f);//
		static Vector3 p1 = new Vector3 (21.7f, 1.0f, 4.7f);//
		static Vector3 p2 = new Vector3 (13.24f, 1.0f, 4.7f);//
		static Vector3 p3 = new Vector3 (-31.97f, 1.0f, -5.0f);//
		static Vector3 p5 = new Vector3 (-21.4f, 1.0f, -5.0f);
		static Vector3 p6 = new Vector3 (43.37f, 1.0f, 4.7f);//
		static Vector3 p7 = new Vector3 (0.63f, 1.0f, 4.7f);//
		static Vector3 p8 = new Vector3 (-42.81f, 1.0f, -5.0f);//

		static Vector3 evaletor1 = new Vector3 (21.7f, 1.0f, 1.31f);
		static Vector3 evaletor2 = new Vector3 (-21.4f, 1.0f, -8.39f);
		static Vector3 s1 = new Vector3 (43.37f, 1.0f, 9.64f);
		static Vector3 s2 = new Vector3 (0.63f, 1.0f, 0.03f);
		static Vector3 s3 = new Vector3 (-42.81f, 1.0f, -9.79f);

		
		static Vector3 pos1 = new Vector3 (365.6F, 21.8F, 248.5F);
		static Vector3 lookat1 = new Vector3 (330.6F, -1.3F, 203.0F);
		static Vector3 pos2 = new Vector3 (307.2F, 36.4F, 247.7F);
		static Vector3 lookat2 = new Vector3 (310.1F, 2.1F, 196.1F);
		static Vector3 pos3 = new Vector3 (289.9F, 28.9F, 260.7F);
		static Vector3 lookat3 = new Vector3 (294.1F, 2.3F, 190.2F);
		static Vector3 pos4 = new Vector3 (332.1F, 19.3F, 244.1F);
		static Vector3 lookat4 = new Vector3 (328.2F, -4.7F, 199.0F);
		static Vector3 pos5 = new Vector3 (313.5F, 36.3F, 236.3F);
		static Vector3 lookat5 = new Vector3 (312.5F, -22.7F, 190.3F);
		
		static Vector3[] thangmay1 = new Vector3[] { start1, p0, p1, evaletor1 };//
		static Vector3[] thangmay2 = new Vector3[] { start3, p3, p5, evaletor2 };

		static Vector3[] thangkeo1 = new Vector3[] { start1, p0, p6, s1 };//
		static Vector3[] thangkeo2 = new Vector3[] { start2, p2, p7, s2 };	//	
		static Vector3[] thangkeo3 = new Vector3[] { start3, p3, p8, s3 };//


		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point6_1 ()
		{
			PositnCamera.Add("thangkeo1",pos1);
			PositnCamera.Add("thangkeo2",pos2);
			PositnCamera.Add("thangkeo3",pos3);
			PositnCamera.Add("thangmay1",pos4);
			PositnCamera.Add("thangmay2",pos5);
			
			
			LookatCamera.Add("thangkeo1",lookat1);
			LookatCamera.Add("thangkeo2",lookat2);
			LookatCamera.Add("thangkeo3",lookat3);
			LookatCamera.Add("thangmay1",lookat4);
			LookatCamera.Add("thangmay2",lookat5);

			dictionary.Add ("thangmay1", thangmay1);
			dictionary.Add ("thangmay2", thangmay2);
			dictionary.Add ("thangkeo1", thangkeo1);
			dictionary.Add ("thangkeo2", thangkeo2);
			dictionary.Add ("thangkeo3", thangkeo3);
		}
	}
}

