//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point3_2
	{
		static Vector3 evalator = new Vector3 (0.0f, 0.0f, -2.6f);
		static Vector3 start = new Vector3 (0.0f, 0.0f, 0.0f);

		static Vector3 p1 = new Vector3 (15.91F, 3.1F, 9.54F);
		static Vector3 p2 = new Vector3 (15.91F, 3.1F, -0.01F);
		static Vector3 p3 = new Vector3 (27.59F, 3.1F, -0.01F);
		static Vector3 p4 = new Vector3 (-15.45F, 3.1F, 0.09F);
		static Vector3 p5 = new Vector3 (-27.09F, 3.1F, 0.09F);
		static Vector3 p6 = new Vector3 (-15.45F, 3.1F, -9.93F);

		
		static Vector3 o1 = new Vector3 (31.5F, 3.1F, 16.6F);
		static Vector3 o2 = new Vector3 (28.2F, 3.1F, 16.6F);
		static Vector3 o3 = new Vector3 (25.0F, 3.1F, 16.6F);
		static Vector3 o4 = new Vector3 (21.7F, 3.1F, 16.6F);
		static Vector3 o5 = new Vector3 (18.3F, 3.1F, 16.6F);
		static Vector3 o6 = new Vector3 (12.2F, 3.1F, 19.4F);
		static Vector3 o7 = new Vector3 (9.4F, 3.1F, 14.9F);
		static Vector3 o8 = new Vector3 (9.4F, 3.1F, 11.5F);
		static Vector3 o9 = new Vector3 (9.4F, 3.1F, 8.2F);
		static Vector3 o10 = new Vector3 (9.4F, 3.1F, 3.8F);
		static Vector3 o11 = new Vector3 (7.1F, 3.1F, -5.2F);
		static Vector3 o12 = new Vector3 (11.7F, 3.1F, -6.8F);
		static Vector3 o13 = new Vector3 (15.0F, 3.1F, -6.8F);
		static Vector3 o14 = new Vector3 (18.3F, 3.1F, -6.8F);
		static Vector3 o15 = new Vector3 (21.6F, 3.1F, -6.8F);
		static Vector3 o16 = new Vector3 (24.9F, 3.1F, -6.8F);
		static Vector3 o17 = new Vector3 (31.1F, 3.1F, -9.6F);
		static Vector3 o18 = new Vector3 (33.8F, 3.1F, -4.8F);
		static Vector3 o19 = new Vector3 (33.8F, 3.1F, -0.9F);
		static Vector3 o20 = new Vector3 (33.8F, 3.1F, 2.9F);
		static Vector3 o21 = new Vector3 (33.8F, 3.1F, 6.9F);
		static Vector3 o22 = new Vector3 (36.1F, 3.1F, 13.9F);
		static Vector3 o23 = new Vector3 (-11.6F, 3.1F, 6.8F);
		static Vector3 o24 = new Vector3 (-14.9F, 3.1F, 6.8F);
		static Vector3 o25 = new Vector3 (-18.2F, 3.1F, 6.8F);
		static Vector3 o26 = new Vector3 (-21.4F, 3.1F, 6.8F);
		static Vector3 o27 = new Vector3 (-24.8F, 3.1F, 6.8F);
		static Vector3 o28 = new Vector3 (-30.9F, 3.1F, 9.6F);
		static Vector3 o29 = new Vector3 (-33.7F, 3.1F, 5.0F);
		static Vector3 o30 = new Vector3 (-33.7F, 3.1F, 1.7F);
		static Vector3 o31 = new Vector3 (-33.7F, 3.1F, -1.6F);
		static Vector3 o32 = new Vector3 (-33.7F, 3.1F, -6.1F);
		static Vector3 o33 = new Vector3 (-36.1F, 3.1F, -13.9F);
		static Vector3 o34 = new Vector3 (-31.4F, 3.1F, -16.6F);
		static Vector3 o35 = new Vector3 (-28.1F, 3.1F, -16.6F);
		static Vector3 o36 = new Vector3 (-24.8F, 3.1F, -16.6F);
		static Vector3 o37 = new Vector3 (-21.5F, 3.1F, -16.6F);
		static Vector3 o38 = new Vector3 (-18.2F, 3.1F, -16.6F);
		static Vector3 o39 = new Vector3 (-12.0F, 3.1F, -19.5F);
		static Vector3 o40 = new Vector3 (-9.3F, 3.1F, -14.7F);
		static Vector3 o41 = new Vector3 (-9.3F, 3.1F, -11.4F);
		static Vector3 o42 = new Vector3 (-9.2F, 3.1F, -8.1F);
		static Vector3 o43 = new Vector3 (-9.3F, 3.1F, -3.6F);
		static Vector3 o44 = new Vector3 (-7.0F, 3.1F, 5.2F);
		
		static Vector3 f1 = new Vector3 (31.5F, 3.1F, 9.54F);
		static Vector3 f2 = new Vector3 (28.2F, 3.1F, 9.54F);
		static Vector3 f3 = new Vector3 (25.0F, 3.1F, 9.54F);
		static Vector3 f4 = new Vector3 (21.7F, 3.1F, 9.54F);
		static Vector3 f5 = new Vector3 (18.3F, 3.1F, 9.54F);
		static Vector3 f6 = new Vector3 (15.91F, 3.1F, 14.9F);
		static Vector3 f7 = new Vector3 (15.91F, 3.1F, 14.9F);
		static Vector3 f8 = new Vector3 (15.91F, 3.1F, 11.5F);
		static Vector3 f9 = new Vector3 (15.91F, 3.1F, 8.2F);
		static Vector3 f10 = new Vector3 (15.91F, 3.1F, 3.8F);
		static Vector3 f11 = new Vector3 (7.1F, 3.1F, -0.01F);
		static Vector3 f12 = new Vector3 (11.7F, 3.1F, -0.01F);
		static Vector3 f13 = new Vector3 (15.0F, 3.1F, -0.01F);
		static Vector3 f14 = new Vector3 (18.3F, 3.1F, -0.01F);
		static Vector3 f15 = new Vector3 (21.6F, 3.1F, -0.01F);
		static Vector3 f16 = new Vector3 (24.9F, 3.1F, -0.01F);
		static Vector3 f17 = new Vector3 (27.59F, 3.1F, -4.8F);
		static Vector3 f18 = new Vector3 (27.59F, 3.1F, -4.8F);
		static Vector3 f19 = new Vector3 (27.59F, 3.1F, -0.9F);
		static Vector3 f20 = new Vector3 (27.59F, 3.1F, 2.9F);
		static Vector3 f21 = new Vector3 (27.59F, 3.1F, 6.9F);
		static Vector3 f22 = new Vector3 (31.5F, 3.1F, 9.54F);
		static Vector3 f23 = new Vector3 (-11.6F, 3.1F, 0.09F);
		static Vector3 f24 = new Vector3 (-14.9F, 3.1F, 0.09F);
		static Vector3 f25 = new Vector3 (-18.2F, 3.1F, 0.09F);
		static Vector3 f26 = new Vector3 (-21.4F, 3.1F, 0.09F);
		static Vector3 f27 = new Vector3 (-24.8F, 3.1F, 0.09F);
		static Vector3 f28 = new Vector3 (-27.09F, 3.1F, 5.0F);
		static Vector3 f29 = new Vector3 (-27.09F, 3.1F, 5.0F);
		static Vector3 f30 = new Vector3 (-27.09F, 3.1F, 1.7F);
		static Vector3 f31 = new Vector3 (-27.09F, 3.1F, -1.6F);
		static Vector3 f32 = new Vector3 (-27.09F, 3.1F, -6.1F);
		static Vector3 f33 = new Vector3 (-31.4F, 3.1F, -9.93F);
		static Vector3 f34 = new Vector3 (-31.4F, 3.1F, -9.93F);
		static Vector3 f35 = new Vector3 (-28.1F, 3.1F, -9.93F);
		static Vector3 f36 = new Vector3 (-24.8F, 3.1F, -9.93F);
		static Vector3 f37 = new Vector3 (-21.5F, 3.1F, -9.93F);
		static Vector3 f38 = new Vector3 (-18.2F, 3.1F, -9.93F);
		static Vector3 f39 = new Vector3 (-15.45F, 3.1F, -14.7F);
		static Vector3 f40 = new Vector3 (-15.45F, 3.1F, -14.7F);
		static Vector3 f41 = new Vector3 (-15.45F, 3.1F, -11.4F);
		static Vector3 f42 = new Vector3 (-15.45F, 3.1F, -8.1F);
		static Vector3 f43 = new Vector3 (-15.45F, 3.1F, -3.6F);
		static Vector3 f44 = new Vector3 (-7.0F, 3.1F, 0.09F);
		
		
		static Vector3[] office1 = new Vector3[] { evalator, start, p2, p1, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator, start, p2, p1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator, start, p2, p1, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator, start, p2, p1, f4, o4 };
		static Vector3[] office5 = new Vector3[] { evalator, start, p2, p1, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator, start, p2, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator, start, p2, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator, start, p2, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator, start, p2, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator, start, p2, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator, start, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator, start, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator, start, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evalator, start, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator, start, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator, start, f16, o16 };
		static Vector3[] office17 = new Vector3[] { evalator, start, p3, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evalator, start, p3, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evalator, start, p3, f19, o19 };
		static Vector3[] office20 = new Vector3[] { evalator, start, p3, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator, start, p3, f21, o21 };	
		
		static Vector3[] office22 = new Vector3[] { evalator, start, p2, p1, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evalator, start, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator, start, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator, start, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evalator, start, f26, o26 };
		static Vector3[] office27 = new Vector3[] { evalator, start, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator, start, p5, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator, start, p5, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator, start, p5, f30, o30 };
		
		static Vector3[] office31 = new Vector3[] { evalator, start, p5, f31, o31 };
		static Vector3[] office32 = new Vector3[] { evalator, start, p5, f32, o32 };
		
		static Vector3[] office33 = new Vector3[] { evalator, start, p4, p6, f33, o33 };
		static Vector3[] office34 = new Vector3[] { evalator, start, p4, p6, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evalator, start, p4, p6, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evalator, start, p4, p6, f36, o36 };
		
		static Vector3[] office37 = new Vector3[] { evalator, start, p4, p6, f37, o37 };
		static Vector3[] office38 = new Vector3[] { evalator, start, p4, p6, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evalator, start, p4, f39, o39 };
		static Vector3[] office40 = new Vector3[] { evalator, start, p4, f40, o40 };
		
		static Vector3[] office41 = new Vector3[] { evalator, start, p4, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evalator, start, p4, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evalator, start, p4, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evalator, start, f44, o44 };


		
		static Vector3 pos1 = new Vector3 (282.1F, 74.6F, 252.8F);
		static Vector3 lookat1 = new Vector3 (283.8F, 14.7F, 191.8F);
		static Vector3 pos2 = new Vector3 (315.8F, 65.1F, 247.2F);
		static Vector3 lookat2 = new Vector3 (295.0F, 0.3F, 191.0F);
		static Vector3 pos3 = new Vector3 (285.8F, 83.7F, 239.2F);
		static Vector3 lookat3 = new Vector3 (286.1F, 2.5F, 191.0F);
		static Vector3 pos4 = new Vector3 (291.1F, 73.6F, 243.9F);
		static Vector3 lookat4 = new Vector3 (291.1F, 5.7F, 191.0F);
		static Vector3 pos5 = new Vector3 (304.4F, 82.5F, 239.1F);
		static Vector3 lookat5 = new Vector3 (291.6F, -2.7F, 191.0F);
		static Vector3 pos6 = new Vector3 (303.6F, 70.3F, 244.2F);
		static Vector3 lookat6 = new Vector3 (296.7F, 8.9F, 191.4F);
		static Vector3 pos7 = new Vector3 (312.8F, 75.8F, 253.3F);
		static Vector3 lookat7 = new Vector3 (301.5F, 5.8F, 191.5F);
		static Vector3 pos8 = new Vector3 (299.0F, 75.7F, 248.0F);
		static Vector3 lookat8 = new Vector3 (296.0F, 3.3F, 189.8F);
		static Vector3 pos9 = new Vector3 (300.7F, 75.2F, 235.7F);
		static Vector3 lookat9 = new Vector3 (302.2F, 0.8F, 188.8F);
		static Vector3 pos10 = new Vector3 (336.5F, 75.2F, 255.5F);
		static Vector3 lookat10 = new Vector3 (297.0F, -1.6F, 187.6F);
		static Vector3 pos11 = new Vector3 (317.2F, 75.6F, 256.9F);
		static Vector3 lookat11 = new Vector3 (290.1F, -7.7F, 185.5F);
		static Vector3 pos12 = new Vector3 (327.7F, 64.3F, 256.8F);
		static Vector3 lookat12 = new Vector3 (302.4F, -1.3F, 185.3F);
		static Vector3 pos13 = new Vector3 (286.0F, 74.4F, 243.3F);
		static Vector3 lookat13 = new Vector3 (287.5F, 0.5F, 185.3F);
		static Vector3 pos14 = new Vector3 (284.2F, 87.6F, 250.9F);
		static Vector3 lookat14 = new Vector3 (288.2F, -2.6F, 185.3F);
		static Vector3 pos15 = new Vector3 (299.0F, 66.4F, 247.6F);
		static Vector3 lookat15 = new Vector3 (298.4F, 1.9F, 185.3F);
		static Vector3 pos16 = new Vector3 (301.5F, 72.4F, 246.9F);
		static Vector3 lookat16 = new Vector3 (289.3F, -0.8F, 186.0F);
		static Vector3 pos17 = new Vector3 (309.6F, 70.7F, 243.4F);
		static Vector3 lookat17 = new Vector3 (293.4F, -4.6F, 184.4F);
		static Vector3 pos18 = new Vector3 (323.3F, 71.2F, 251.0F);
		static Vector3 lookat18 = new Vector3 (294.4F, -7.4F, 185.1F);
		static Vector3 pos19 = new Vector3 (291.3F, 77.0F, 237.2F);
		static Vector3 lookat19 = new Vector3 (294.7F, 1.2F, 186.2F);
		static Vector3 pos20 = new Vector3 (310.8F, 84.9F, 245.6F);
		static Vector3 lookat20 = new Vector3 (294.9F, 0.2F, 187.3F);
		static Vector3 pos21 = new Vector3 (307.6F, 78.1F, 247.4F);
		static Vector3 lookat21 = new Vector3 (294.7F, -1.9F, 188.4F);
		static Vector3 pos22 = new Vector3 (302.4F, 81.3F, 242.1F);
		static Vector3 lookat22 = new Vector3 (290.4F, 2.1F, 190.6F);
		static Vector3 pos23 = new Vector3 (263.7F, 68.5F, 236.0F);
		static Vector3 lookat23 = new Vector3 (285.6F, 12.7F, 187.5F);
		static Vector3 pos24 = new Vector3 (263.2F, 63.8F, 235.8F);
		static Vector3 lookat24 = new Vector3 (283.2F, 11.5F, 187.5F);
		static Vector3 pos25 = new Vector3 (261.6F, 69.8F, 228.6F);
		static Vector3 lookat25 = new Vector3 (283.2F, 8.8F, 187.5F);
		static Vector3 pos26 = new Vector3 (253.8F, 78.1F, 237.1F);
		static Vector3 lookat26 = new Vector3 (288.7F, 3.4F, 187.5F);
		static Vector3 pos27 = new Vector3 (260.8F, 78.7F, 244.6F);
		static Vector3 lookat27 = new Vector3 (281.6F, 11.2F, 187.5F);
		static Vector3 pos28 = new Vector3 (272.3F, 79.9F, 236.6F);
		static Vector3 lookat28 = new Vector3 (288.7F, 13.5F, 188.6F);
		static Vector3 pos29 = new Vector3 (263.5F, 79.7F, 229.7F);
		static Vector3 lookat29 = new Vector3 (284.5F, 9.9F, 187.9F);
		static Vector3 pos30 = new Vector3 (266.2F, 72.9F, 227.4F);
		static Vector3 lookat30 = new Vector3 (282.3F, 12.4F, 187.0F);
		static Vector3 pos31 = new Vector3 (269.5F, 76.9F, 234.3F);
		static Vector3 lookat31 = new Vector3 (285.6F, 7.9F, 186.0F);
		static Vector3 pos32 = new Vector3 (269.4F, 67.5F, 237.1F);
		static Vector3 lookat32 = new Vector3 (285.5F, 8.5F, 184.7F);
		static Vector3 pos33 = new Vector3 (266.8F, 64.0F, 238.8F);
		static Vector3 lookat33 = new Vector3 (284.4F, 6.4F, 182.3F);
		static Vector3 pos34 = new Vector3 (278.1F, 76.9F, 239.4F);
		static Vector3 lookat34 = new Vector3 (287.5F, 4.4F, 182.0F);
		static Vector3 pos35 = new Vector3 (269.2F, 66.4F, 237.3F);
		static Vector3 lookat35 = new Vector3 (284.2F, 6.0F, 182.0F);
		static Vector3 pos36 = new Vector3 (269.6F, 62.5F, 236.0F);
		static Vector3 lookat36 = new Vector3 (287.1F, 5.6F, 182.0F);
		static Vector3 pos37 = new Vector3 (268.4F, 67.4F, 239.1F);
		static Vector3 lookat37 = new Vector3 (283.4F, -0.3F, 182.0F);
		static Vector3 pos38 = new Vector3 (269.9F, 81.9F, 239.6F);
		static Vector3 lookat38 = new Vector3 (290.8F, -4.3F, 182.0F);
		static Vector3 pos39 = new Vector3 (275.0F, 81.8F, 227.3F);
		static Vector3 lookat39 = new Vector3 (293.2F, -4.7F, 181.6F);
		static Vector3 pos40 = new Vector3 (279.5F, 75.2F, 238.3F);
		static Vector3 lookat40 = new Vector3 (293.1F, -0.2F, 182.3F);
		static Vector3 pos41 = new Vector3 (271.2F, 73.1F, 233.2F);
		static Vector3 lookat41 = new Vector3 (286.7F, 3.3F, 183.2F);
		static Vector3 pos42 = new Vector3 (271.2F, 77.5F, 234.5F);
		static Vector3 lookat42 = new Vector3 (288.0F, 1.3F, 184.2F);
		static Vector3 pos43 = new Vector3 (266.6F, 70.5F, 233.1F);
		static Vector3 lookat43 = new Vector3 (291.8F, 1.7F, 185.5F);
		static Vector3 pos44 = new Vector3 (262.6F, 77.2F, 234.4F);
		static Vector3 lookat44 = new Vector3 (282.2F, 2.7F, 187.3F);

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point3_2 ()
		{

			
			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);
			PositnCamera.Add("office21",pos21);
			PositnCamera.Add("office22",pos22);
			PositnCamera.Add("office23",pos23);
			PositnCamera.Add("office24",pos24);
			PositnCamera.Add("office25",pos25);
			PositnCamera.Add("office26",pos26);
			PositnCamera.Add("office27",pos27);
			PositnCamera.Add("office28",pos28);
			PositnCamera.Add("office29",pos29);
			PositnCamera.Add("office30",pos30);
			PositnCamera.Add("office31",pos31);
			PositnCamera.Add("office32",pos32);
			PositnCamera.Add("office33",pos33);
			PositnCamera.Add("office34",pos34);
			PositnCamera.Add("office35",pos35);
			PositnCamera.Add("office36",pos36);
			PositnCamera.Add("office37",pos37);
			PositnCamera.Add("office38",pos38);
			PositnCamera.Add("office39",pos39);
			PositnCamera.Add("office40",pos40);
			PositnCamera.Add("office41",pos41);
			PositnCamera.Add("office42",pos42);
			PositnCamera.Add("office43",pos43);
			PositnCamera.Add("office44",pos44);

			
			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);
			LookatCamera.Add("office9",lookat9);
			LookatCamera.Add("office10",lookat10);
			LookatCamera.Add("office11",lookat11);
			LookatCamera.Add("office12",lookat12);
			LookatCamera.Add("office13",lookat13);
			LookatCamera.Add("office14",lookat14);
			LookatCamera.Add("office15",lookat15);
			LookatCamera.Add("office16",lookat16);
			LookatCamera.Add("office17",lookat17);
			LookatCamera.Add("office18",lookat18);
			LookatCamera.Add("office19",lookat19);
			LookatCamera.Add("office20",lookat20);
			LookatCamera.Add("office21",lookat21);
			LookatCamera.Add("office22",lookat22);
			LookatCamera.Add("office23",lookat23);
			LookatCamera.Add("office24",lookat24);
			LookatCamera.Add("office25",lookat25);
			LookatCamera.Add("office26",lookat26);
			LookatCamera.Add("office27",lookat27);
			LookatCamera.Add("office28",lookat28);
			LookatCamera.Add("office29",lookat29);
			LookatCamera.Add("office30",lookat30);
			LookatCamera.Add("office31",lookat31);
			LookatCamera.Add("office32",lookat32);
			LookatCamera.Add("office33",lookat33);
			LookatCamera.Add("office34",lookat34);
			LookatCamera.Add("office35",lookat35);
			LookatCamera.Add("office36",lookat36);
			LookatCamera.Add("office37",lookat37);
			LookatCamera.Add("office38",lookat38);
			LookatCamera.Add("office39",lookat39);
			LookatCamera.Add("office40",lookat40);
			LookatCamera.Add("office41",lookat41);
			LookatCamera.Add("office42",lookat42);
			LookatCamera.Add("office43",lookat43);
			LookatCamera.Add("office44",lookat44);

			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
		}
	}
}

