//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point6_1
	{
		static Vector3 start = new Vector3 (61.15f, 4.0f, 13.29f);
		static Vector3 p0 = new Vector3 (47.16f, 4.0f, 13.29f);
		static Vector3 p1 = new Vector3 (47.16f, 4.0f, 4.7f);		
		static Vector3 p2 = new Vector3 (21.7f, 4.0f, 4.7f);	
		static Vector3 p3 = new Vector3 (0.24f, 4.0f, 4.7f);
		static Vector3 p4 = new Vector3 (0.24f, 4.0f, -5.0f);
		static Vector3 p5 = new Vector3 (-21.4f, 4.0f, -5.0f);
		static Vector3 p6 = new Vector3 (47.16f, 4.0f, 9.64f);
		static Vector3 p7 = new Vector3 (0.63f, 4.0f, 4.7f);
		static Vector3 p8 = new Vector3 (-42.81f, 4.0f, -5.0f);

		static Vector3 evaletor1 = new Vector3 (21.7f, 4.0f, 1.31f);
		static Vector3 evaletor2 = new Vector3 (-21.4f, 4.0f, -8.39f);
		static Vector3 s1 = new Vector3 (43.37f, 4.0f, 9.64f);
		static Vector3 s2 = new Vector3 (0.63f, 4.0f, 0.03f);
		static Vector3 s3 = new Vector3 (-42.81f, 4.0f, -9.79f);
		
		static Vector3[] thangmay1 = new Vector3[] { start, p0, p1, p2, evaletor1 };	
		static Vector3[] thangmay2 = new Vector3[] { start, p0, p1, p2, p3, p4, p5, evaletor2 };

		static Vector3[] thangkeo1 = new Vector3[] { start, p0, p6, s1 };
		static Vector3[] thangkeo2 = new Vector3[] { start, p0, p1, p2, p7, s2 };		
		static Vector3[] thangkeo3 = new Vector3[] { start, p0, p1, p2, p3, p4, p5, p8, s3 };


		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();

		public Point6_1 ()
		{
			dictionary.Add ("thangmay1", thangmay1);
			dictionary.Add ("thangmay2", thangmay2);
			dictionary.Add ("thangkeo1", thangkeo1);
			dictionary.Add ("thangkeo2", thangkeo2);
			dictionary.Add ("thangkeo3", thangkeo3);
		}
	}
}

