//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point6_4handicap
	{
		
		static Vector3 f1 = new Vector3 (49.3F, 4.0F, 14.5F);
		static Vector3 f2 = new Vector3 (45.4F, 4.0F, 14.5F);
		static Vector3 f3 = new Vector3 (41.4F, 4.0F, 14.5F);
		static Vector3 f4 = new Vector3 (37.4F, 4.0F, 14.5F);
		static Vector3 f5 = new Vector3 (37.4F, 4.0F, 14.5F);
		static Vector3 f6 = new Vector3 (37.9F, 4.0F, 11.7F);
		static Vector3 f7 = new Vector3 (37.9F, 4.0F, 7.6F);
		static Vector3 f8 = new Vector3 (33.5F, 4.0F, 4.9F);
		static Vector3 f9 = new Vector3 (37.4F, 4.0F, 4.9F);
		static Vector3 f10 = new Vector3 (41.5F, 4.0F, 4.9F);
		static Vector3 f11 = new Vector3 (45.4F, 4.0F, 4.9F);
		static Vector3 f12 = new Vector3 (49.3F, 4.0F, 4.9F);
		static Vector3 f13 = new Vector3 (49.3F, 4.0F, 4.9F);
		static Vector3 f14 = new Vector3 (48.9F, 4.0F, 7.8F);
		static Vector3 f15 = new Vector3 (48.9F, 4.0F, 11.7F);
		static Vector3 f16 = new Vector3 (49.3F, 4.0F, 14.5F);
		static Vector3 f17 = new Vector3 (10.0F, 4.0F, 4.8F);
		static Vector3 f18 = new Vector3 (6.2F, 4.0F, 4.8F);
		static Vector3 f19 = new Vector3 (2.3F, 4.0F, 4.8F);
		static Vector3 f20 = new Vector3 (-1.7F, 4.0F, 4.8F);
		static Vector3 f21 = new Vector3 (-5.6F, 4.0F, 4.8F);
		static Vector3 f22 = new Vector3 (-5.6F, 4.0F, 4.8F);
		static Vector3 f23 = new Vector3 (-5.2F, 4.0F, -0.1F);
		static Vector3 f24 = new Vector3 (-9.5F, 4.0F, -4.9F);
		static Vector3 f25 = new Vector3 (-5.6F, 4.0F, -4.9F);
		static Vector3 f26 = new Vector3 (-1.7F, 4.0F, -4.9F);
		static Vector3 f27 = new Vector3 (2.3F, 4.0F, -4.9F);
		static Vector3 f28 = new Vector3 (6.2F, 4.0F, -4.9F);
		static Vector3 f29 = new Vector3 (6.2F, 4.0F, -4.9F);
		static Vector3 f30 = new Vector3 (5.7F, 4.0F, -1.9F);
		static Vector3 f31 = new Vector3 (5.7F, 4.0F, 2.0F);
		static Vector3 f32 = new Vector3 (-32.9F, 4.0F, -4.9F);
		static Vector3 f33 = new Vector3 (-36.9F, 4.0F, -4.9F);
		static Vector3 f34 = new Vector3 (-40.8F, 4.0F, -4.9F);
		static Vector3 f35 = new Vector3 (-44.8F, 4.0F, -4.9F);
		static Vector3 f36 = new Vector3 (-48.7F, 4.0F, -4.9F);
		static Vector3 f37 = new Vector3 (-48.7F, 4.0F, -4.9F);
		static Vector3 f38 = new Vector3 (-48.2F, 4.0F, -7.7F);
		static Vector3 f39 = new Vector3 (-48.2F, 4.0F, -11.6F);
		static Vector3 f40 = new Vector3 (-48.6F, 4.0F, -14.5F);
		static Vector3 f41 = new Vector3 (-48.6F, 4.0F, -14.5F);
		static Vector3 f42 = new Vector3 (-44.8F, 4.0F, -14.5F);
		static Vector3 f43 = new Vector3 (-40.8F, 4.0F, -14.5F);
		static Vector3 f44 = new Vector3 (-36.9F, 4.0F, -14.5F);
		static Vector3 f45 = new Vector3 (-36.9F, 4.0F, -14.5F);
		static Vector3 f46 = new Vector3 (-37.4F, 4.0F, -11.7F);
		static Vector3 f47 = new Vector3 (-37.4F, 4.0F, -7.7F);
		
		
		static Vector3 o1 = new Vector3 (49.3F, 4.0F, 18.9F);
		static Vector3 o2 = new Vector3 (45.4F, 4.0F, 18.9F);
		static Vector3 o3 = new Vector3 (41.4F, 4.0F, 18.9F);
		static Vector3 o4 = new Vector3 (37.4F, 4.0F, 18.9F);
		static Vector3 o5 = new Vector3 (33.4F, 4.0F, 17.9F);
		static Vector3 o6 = new Vector3 (33.6F, 4.0F, 11.7F);
		static Vector3 o7 = new Vector3 (33.6F, 4.0F, 7.6F);
		static Vector3 o8 = new Vector3 (33.5F, 4.0F, 0.6F);
		static Vector3 o9 = new Vector3 (37.4F, 4.0F, 0.6F);
		static Vector3 o10 = new Vector3 (41.5F, 4.0F, 0.6F);
		static Vector3 o11 = new Vector3 (45.4F, 4.0F, 0.6F);
		static Vector3 o12 = new Vector3 (49.3F, 4.0F, 0.6F);
		static Vector3 o13 = new Vector3 (53.4F, 4.0F, 1.6F);
		static Vector3 o14 = new Vector3 (53.2F, 4.0F, 7.8F);
		static Vector3 o15 = new Vector3 (53.2F, 4.0F, 11.7F);
		static Vector3 o16 = new Vector3 (53.4F, 4.0F, 17.7F);
		static Vector3 o17 = new Vector3 (10.0F, 4.0F, 9.1F);
		static Vector3 o18 = new Vector3 (6.2F, 4.0F, 9.1F);
		static Vector3 o19 = new Vector3 (2.3F, 4.0F, 9.1F);
		static Vector3 o20 = new Vector3 (-1.7F, 4.0F, 9.1F);
		static Vector3 o21 = new Vector3 (-5.6F, 4.0F, 9.1F);
		static Vector3 o22 = new Vector3 (-9.7F, 4.0F, 7.9F);
		static Vector3 o23 = new Vector3 (-9.5F, 4.0F, -0.1F);
		static Vector3 o24 = new Vector3 (-9.5F, 4.0F, -9.2F);
		static Vector3 o25 = new Vector3 (-5.6F, 4.0F, -9.2F);
		static Vector3 o26 = new Vector3 (-1.7F, 4.0F, -9.2F);
		static Vector3 o27 = new Vector3 (2.3F, 4.0F, -9.2F);
		static Vector3 o28 = new Vector3 (6.2F, 4.0F, -9.2F);
		static Vector3 o29 = new Vector3 (10.2F, 4.0F, -8.0F);
		static Vector3 o30 = new Vector3 (10.0F, 4.0F, -1.9F);
		static Vector3 o31 = new Vector3 (10.0F, 4.0F, 2.0F);
		static Vector3 o32 = new Vector3 (-32.9F, 4.0F, -0.6F);
		static Vector3 o33 = new Vector3 (-36.9F, 4.0F, -0.6F);
		static Vector3 o34 = new Vector3 (-40.8F, 4.0F, -0.6F);
		static Vector3 o35 = new Vector3 (-44.8F, 4.0F, -0.6F);
		static Vector3 o36 = new Vector3 (-48.7F, 4.0F, -0.6F);
		static Vector3 o37 = new Vector3 (-53.0F, 4.0F, -1.8F);
		static Vector3 o38 = new Vector3 (-52.5F, 4.0F, -7.7F);
		static Vector3 o39 = new Vector3 (-52.5F, 4.0F, -11.6F);
		static Vector3 o40 = new Vector3 (-53.0F, 4.0F, -18.0F);
		static Vector3 o41 = new Vector3 (-48.6F, 4.0F, -18.8F);
		static Vector3 o42 = new Vector3 (-44.8F, 4.0F, -18.8F);
		static Vector3 o43 = new Vector3 (-40.8F, 4.0F, -18.8F);
		static Vector3 o44 = new Vector3 (-36.9F, 4.0F, -18.8F);
		static Vector3 o45 = new Vector3 (-32.6F, 4.0F, -18.0F);
		static Vector3 o46 = new Vector3 (-33.0F, 4.0F, -11.7F);
		static Vector3 o47 = new Vector3 (-33.0F, 4.0F, -7.7F);

		public static Vector3 evalator1 = new Vector3 (43.37f, 4.0f, 9.64f);

		public static Vector3 evalator2 = new Vector3 (0.63f, 4.0f, 0.03f);

		public static Vector3 evalator3 = new Vector3 (-42.81f, 4.0f, -9.79f);
		
		
		static Vector3[] office1 = new Vector3[] { evalator1, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, f3, o3 };		
		static Vector3[] office4 = new Vector3[] { evalator1, f4, o4 };		
		static Vector3[] office5 = new Vector3[] { evalator1, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator1, f6, o6 };		
		static Vector3[] office7 = new Vector3[] { evalator1, f7, o7 };		
		static Vector3[] office8 = new Vector3[] { evalator1, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator1, f9, o9 };		
		static Vector3[] office10 = new Vector3[] { evalator1, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator1, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator1, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator1, f13, o13 };		
		static Vector3[] office14 = new Vector3[] { evalator1, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator1, f15, o15 };		
		static Vector3[] office16 = new Vector3[] { evalator1, f16, o16 };
		
		static Vector3[] office17 = new Vector3[] { evalator2, f17, o17 };		
		static Vector3[] office18 = new Vector3[] { evalator2, f18, o18 };		
		static Vector3[] office19 = new Vector3[] { evalator2, f19, o19 };		
		static Vector3[] office20 = new Vector3[] { evalator2, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator2, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator2, f22, o22 };		
		static Vector3[] office23 = new Vector3[] { evalator2, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator2, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator2, f25, o25 };		
		static Vector3[] office26 = new Vector3[] { evalator2, f26, o26 };		
		static Vector3[] office27 = new Vector3[] { evalator2, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator2, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator2, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator2, f30, o30 };		
		static Vector3[] office31 = new Vector3[] { evalator2, f31, o31 };
		
		static Vector3[] office32 = new Vector3[] { evalator3, f32, o32 };		
		static Vector3[] office33 = new Vector3[] { evalator3, f33, o33 };
		static Vector3[] office34 = new Vector3[] { evalator3, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evalator3, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evalator3, f36, o36 };		
		static Vector3[] office37 = new Vector3[] { evalator3, f37, o37 };		
		static Vector3[] office38 = new Vector3[] { evalator3, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evalator3, f39, o39 };		
		static Vector3[] office40 = new Vector3[] { evalator3, f40, o40 };		
		static Vector3[] office41 = new Vector3[] { evalator3, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evalator3, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evalator3, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evalator3, f44, o44 };
		static Vector3[] office45 = new Vector3[] { evalator3, f45, o45 };
		static Vector3[] office46 = new Vector3[] { evalator3, f46, o46 };
		static Vector3[] office47 = new Vector3[] { evalator3, f47, o47 };
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();

		public Point6_4handicap ()
		{
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
			dictionary.Add("office45",office45);
			dictionary.Add("office46",office46);
			dictionary.Add("office47",office47);
		}
	}
}

