//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point3_1
	{
		public static Vector3 begin = new Vector3 (38.7f, 1.5f, 10.34f);
		static Vector3 evalator = new Vector3 (0.0f, 0.0f, -2.6f);
		static Vector3 start = new Vector3 (0.0f, 0.0f, 0.0f);

		
		public static Vector3 evalator1 = new Vector3 (21.79f, 1.5f, 4.18f);
		public static Vector3 evalator2 = new Vector3 (-20.63f, 1.5f, -5.13f);
		
		public static Vector3 p2 = new Vector3 (25.83f, 1.5f, 0f);
		public static Vector3 p1 = new Vector3 (25.83f, 1.5f, 10.34f);
		public static Vector3 p3 = new Vector3 (-20.63f, 1.5f, 0f);
		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		static Vector3[] thangmay = new Vector3[] { begin, p1, p2, start, evalator };	
		static Vector3[] thangmay1 = new Vector3[] { begin, p1, evalator1 };	
		static Vector3[] thangmay2 = new Vector3[] { begin, p1, p2, p3, evalator2 };	
		public Point3_1 ()
		{
			dictionary.Add ("thangmay", thangmay);
			dictionary.Add ("thangkeo1", thangmay1);
			dictionary.Add ("thangkeo2", thangmay2);
		}
	}
}

