//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point6_3
	{
		public static Vector3 start1 = new Vector3 (22.6f, 9.5f, 4.7f);
		public static Vector3 evalator1 = new Vector3 (22.6f, 9.5f, 1.31f);
		public static Vector3 start2 = new Vector3 (-21.2f, 9.5f, -4.9f);
		public static Vector3 evalator2 = new Vector3 (-21.2f, 9.5f, -8.29f);

		
		static Vector3 p1 = new Vector3 (37.55F, 3.9F, 14.4F);
		static Vector3 p2 = new Vector3 (37.55F, 3.9F, 4.7F);
		static Vector3 p3 = new Vector3 (49.13F, 3.9F, 4.7F);
		static Vector3 p4 = new Vector3 (-5.65F, 3.9F, -4.9F);
		static Vector3 p5 = new Vector3 (-5.65F, 3.9F, 4.7F);
		static Vector3 p6 = new Vector3 (5.85F, 3.9F, -4.9F);
		static Vector3 p7 = new Vector3 (5.85F, 3.9F, 4.7F);
		
		static Vector3 f1 = new Vector3 (53.4F, 3.9F, 14.4F);
		static Vector3 f2 = new Vector3 (50.0F, 3.9F, 14.4F);
		static Vector3 f3 = new Vector3 (46.8F, 3.9F, 14.4F);
		static Vector3 f4 = new Vector3 (43.4F, 3.9F, 14.4F);
		static Vector3 f5 = new Vector3 (40.1F, 3.9F, 14.4F);
		static Vector3 f6 = new Vector3 (37.55F, 3.9F, 19.6F);
		static Vector3 f7 = new Vector3 (37.55F, 3.9F, 19.6F);
		static Vector3 f8 = new Vector3 (37.55F, 3.9F, 16.3F);
		static Vector3 f9 = new Vector3 (37.55F, 3.9F, 12.9F);
		static Vector3 f10 = new Vector3 (37.55F, 3.9F, 8.5F);
		static Vector3 f11 = new Vector3 (28.9F, 3.9F, 4.7F);
		static Vector3 f12 = new Vector3 (33.5F, 3.9F,4.7F);
		static Vector3 f13 = new Vector3 (36.9F, 3.9F,4.7F);
		static Vector3 f14 = new Vector3 (40.1F, 3.9F,4.7F);
		static Vector3 f15 = new Vector3 (43.5F, 3.9F,4.7F);
		static Vector3 f16 = new Vector3 (46.8F, 3.9F,4.7F);
		static Vector3 f17 = new Vector3 (49.13F, 3.9F, 0.1F);
		static Vector3 f18 = new Vector3 (49.13F, 3.9F, 0.1F);
		static Vector3 f19 = new Vector3 (49.13F, 3.9F, 3.9F);
		static Vector3 f20 = new Vector3 (49.13F, 3.9F, 7.7F);
		static Vector3 f21 = new Vector3 (49.13F, 3.9F, 11.7F);
		static Vector3 f22 = new Vector3 (53.4F, 3.9F, 14.4F);
		static Vector3 f23 = new Vector3 (10.2F, 3.9F, 4.7F);
		static Vector3 f24 = new Vector3 (6.8F, 3.9F, 4.7F);
		static Vector3 f25 = new Vector3 (3.6F, 3.9F, 4.7F);
		static Vector3 f26 = new Vector3 (0.3F, 3.9F, 4.7F);
		static Vector3 f27 = new Vector3 (-3.0F, 3.9F, 4.7F);
		static Vector3 f28 = new Vector3 (-5.65F, 3.9F, 10.1F);
		static Vector3 f29 = new Vector3 (-5.65F, 3.9F, 10.1F);
		static Vector3 f30 = new Vector3 (-5.65F, 3.9F, 6.8F);
		static Vector3 f31 = new Vector3 (-5.65F, 3.9F, 3.4F);
		static Vector3 f32 = new Vector3 (-5.65F, 3.9F, -1.0F);
		static Vector3 f33 = new Vector3 (-14.3F, 3.9F, -4.9F);
		static Vector3 f34 = new Vector3 (-9.7F, 3.9F, -4.9F);
		static Vector3 f35 = new Vector3 (-6.3F, 3.9F, -4.9F);
		static Vector3 f36 = new Vector3 (-3.0F, 3.9F, -4.9F);
		static Vector3 f37 = new Vector3 (0.3F, 3.9F, -4.9F);
		static Vector3 f38 = new Vector3 (3.64F, 3.9F, -4.9F);
		static Vector3 f39 = new Vector3 (5.85F, 3.9F, -9.4F);
		static Vector3 f40 = new Vector3 (5.85F, 3.9F, -9.4F);
		static Vector3 f41 = new Vector3 (5.85F, 3.9F, -5.6F);
		static Vector3 f42 = new Vector3 (5.85F, 3.9F, -1.8F);
		static Vector3 f43 = new Vector3 (5.85F, 3.9F,4.92F);
		static Vector3 f44 = new Vector3 (14.7F, 3.9F, 4.7F);
		static Vector3 f45 = new Vector3 (-28.3F, 3.9F, -4.9F);
		static Vector3 f46 = new Vector3 (-32.9F, 3.9F, -4.9F);
		static Vector3 f47 = new Vector3 (-36.2F, 3.9F, -4.9F);
		static Vector3 f48 = new Vector3 (-39.5F, 3.9F, -4.9F);
		static Vector3 f49 = new Vector3 (-42.8F, 3.9F, -4.9F);
		static Vector3 f50 = new Vector3 (-46.1F, 3.9F, -4.9F);
		static Vector3 f51 = new Vector3 (-48.77F, 3.9F, 0.0F);
		static Vector3 f52 = new Vector3 (-48.77F, 3.9F, 0.0F);
		static Vector3 f53 = new Vector3 (-48.77F, 3.9F, -3.8F);
		static Vector3 f54 = new Vector3 (-48.77F, 3.9F, -7.7F);
		static Vector3 f55 = new Vector3 (-50.7F, 3.9F, -11.7F);
		static Vector3 f56 = new Vector3 (-52.7F, 3.9F, -14.32F);
		static Vector3 f57 = new Vector3 (-52.7F, 3.9F, -14.32F);
		static Vector3 f58 = new Vector3 (-49.4F, 3.9F, -14.32F);
		static Vector3 f59 = new Vector3 (-46.1F, 3.9F, -14.32F);
		static Vector3 f60 = new Vector3 (-42.7F, 3.9F, -14.32F);
		static Vector3 f61 = new Vector3 (-39.4F, 3.9F, -14.32F);
		static Vector3 f62 = new Vector3 (-37.1F, 3.9F, -19.4F);
		static Vector3 f63 = new Vector3 (-37.1F, 3.9F, -19.4F);
		static Vector3 f64 = new Vector3 (-37.1F, 3.9F, -15.6F);
		static Vector3 f65 = new Vector3 (-37.1F, 3.9F, -11.8F);
		static Vector3 f66 = new Vector3 (-37.1F, 3.9F, -7.8F);
		
		static Vector3 o1 = new Vector3 (53.4F, 3.9F, 21.4F);
		static Vector3 o2 = new Vector3 (50.0F, 3.9F, 21.4F);
		static Vector3 o3 = new Vector3 (46.8F, 3.9F, 21.4F);
		static Vector3 o4 = new Vector3 (43.4F, 3.9F, 21.4F);
		static Vector3 o5 = new Vector3 (40.1F, 3.9F, 21.4F);
		static Vector3 o6 = new Vector3 (34.0F, 3.9F, 24.3F);
		static Vector3 o7 = new Vector3 (31.3F, 3.9F, 19.6F);
		static Vector3 o8 = new Vector3 (31.3F, 3.9F, 16.3F);
		static Vector3 o9 = new Vector3 (31.3F, 3.9F, 12.9F);
		static Vector3 o10 = new Vector3 (31.2F, 3.9F, 8.5F);
		static Vector3 o11 = new Vector3 (28.9F, 3.9F, -0.3F);
		static Vector3 o12 = new Vector3 (33.5F, 3.9F, -2.1F);
		static Vector3 o13 = new Vector3 (36.9F, 3.9F, -2.1F);
		static Vector3 o14 = new Vector3 (40.1F, 3.9F, -2.1F);
		static Vector3 o15 = new Vector3 (43.5F, 3.9F, -2.1F);
		static Vector3 o16 = new Vector3 (46.8F, 3.9F, -2.1F);
		static Vector3 o17 = new Vector3 (53.0F, 3.9F, -4.9F);
		static Vector3 o18 = new Vector3 (55.7F, 3.9F, 0.1F);
		static Vector3 o19 = new Vector3 (55.7F, 3.9F, 3.9F);
		static Vector3 o20 = new Vector3 (55.7F, 3.9F, 7.7F);
		static Vector3 o21 = new Vector3 (55.7F, 3.9F, 11.7F);
		static Vector3 o22 = new Vector3 (57.9F, 3.9F, 18.7F);
		static Vector3 o23 = new Vector3 (10.2F, 3.9F, 11.9F);
		static Vector3 o24 = new Vector3 (6.8F, 3.9F, 11.9F);
		static Vector3 o25 = new Vector3 (3.6F, 3.9F, 11.9F);
		static Vector3 o26 = new Vector3 (0.3F, 3.9F, 11.9F);
		static Vector3 o27 = new Vector3 (-3.0F, 3.9F, 11.9F);
		static Vector3 o28 = new Vector3 (-9.2F, 3.9F, 14.8F);
		static Vector3 o29 = new Vector3 (-11.9F, 3.9F, 10.1F);
		static Vector3 o30 = new Vector3 (-11.9F, 3.9F, 6.8F);
		static Vector3 o31 = new Vector3 (-11.9F, 3.9F, 3.4F);
		static Vector3 o32 = new Vector3 (-11.9F, 3.9F, -1.0F);
		static Vector3 o33 = new Vector3 (-14.3F, 3.9F, -9.8F);
		static Vector3 o34 = new Vector3 (-9.7F, 3.9F, -11.6F);
		static Vector3 o35 = new Vector3 (-6.3F, 3.9F, -11.6F);
		static Vector3 o36 = new Vector3 (-3.0F, 3.9F, -11.6F);
		static Vector3 o37 = new Vector3 (0.3F, 3.9F, -11.6F);
		static Vector3 o38 = new Vector3 (3.6F, 3.9F, -11.6F);
		static Vector3 o39 = new Vector3 (9.8F, 3.9F, -14.4F);
		static Vector3 o40 = new Vector3 (12.5F, 3.9F, -9.4F);
		static Vector3 o41 = new Vector3 (12.5F, 3.9F, -5.6F);
		static Vector3 o42 = new Vector3 (12.5F, 3.9F, -1.8F);
		static Vector3 o43 = new Vector3 (12.5F, 3.9F,2.2F);
		static Vector3 o44 = new Vector3 (14.7F, 3.9F, 10.1F);
		static Vector3 o45 = new Vector3 (-28.3F, 3.9F, 0.5F);
		static Vector3 o46 = new Vector3 (-32.9F, 3.9F, 1.9F);
		static Vector3 o47 = new Vector3 (-36.2F, 3.9F, 1.9F);
		static Vector3 o48 = new Vector3 (-39.5F, 3.9F, 1.9F);
		static Vector3 o49 = new Vector3 (-42.8F, 3.9F, 1.9F);
		static Vector3 o50 = new Vector3 (-46.1F, 3.9F, 1.9F);
		static Vector3 o51 = new Vector3 (-52.2F, 3.9F, 4.8F);
		static Vector3 o52 = new Vector3 (-54.9F, 3.9F, 0.0F);
		static Vector3 o53 = new Vector3 (-54.9F, 3.9F, -3.8F);
		static Vector3 o54 = new Vector3 (-54.9F, 3.9F, -7.7F);
		static Vector3 o55 = new Vector3 (-55.0F, 3.9F, -11.7F);
		static Vector3 o56 = new Vector3 (-57.3F, 3.9F, -19.2F);
		static Vector3 o57 = new Vector3 (-52.7F, 3.9F, -21.6F);
		static Vector3 o58 = new Vector3 (-49.4F, 3.9F, -21.6F);
		static Vector3 o59 = new Vector3 (-46.1F, 3.9F, -21.6F);
		static Vector3 o60 = new Vector3 (-42.7F, 3.9F, -21.6F);
		static Vector3 o61 = new Vector3 (-39.4F, 3.9F, -21.6F);
		static Vector3 o62 = new Vector3 (-33.2F, 3.9F, -24.4F);
		static Vector3 o63 = new Vector3 (-30.5F, 3.9F, -19.4F);
		static Vector3 o64 = new Vector3 (-30.5F, 3.9F, -15.6F);
		static Vector3 o65 = new Vector3 (-30.5F, 3.9F, -11.8F);
		static Vector3 o66 = new Vector3 (-30.5F, 3.9F, -7.8F);

		
		static Vector3[] office1 = new Vector3[] { evalator1, start1, p2, p1, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, start1, p2, p1, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, start1, p2, p1, f3, o3 };
	
		static Vector3[] office4 = new Vector3[] { evalator1, start1, p2, p1, f4, o4 };
		static Vector3[] office5 = new Vector3[] { evalator1, start1, p2, p1, f5, o5 };

		static Vector3[] office6 = new Vector3[] { evalator1, start1, p2, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator1, start1, p2, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator1, start1, p2, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator1, start1, p2, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator1, start1, p2, f10, o10 };

		static Vector3[] office11 = new Vector3[] { evalator1, start1, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator1, start1, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator1, start1, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evalator1, start1, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator1, start1,  f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator1, start1, f16, o16 };

		static Vector3[] office17 = new Vector3[] { evalator1, start1, p3,  f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evalator1, start1, p3, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evalator1, start1, f19, o19 };

		static Vector3[] office20 = new Vector3[] { evalator1, start1, p3, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator1, start1, p3, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator1, start1, p2, p1, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evalator1, start1, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator1, start1, f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator1, start1, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evalator2, start2, p4, p5, f26, o26 };
		static Vector3[] office27 = new Vector3[] { evalator2, start2, p4, p5, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator2, start2, p4, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator2, start2, p4, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator2, start2, p4, f30, o30 };
		
		static Vector3[] office31 = new Vector3[] { evalator2, start2, p4,  f31, o31 };
		static Vector3[] office32 = new Vector3[] { evalator2, start2, p4, f32, o32 };
		
		static Vector3[] office33 = new Vector3[] { evalator2, start2, f33, o33 };
		static Vector3[] office34 = new Vector3[] { evalator2, start2, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evalator2, start2, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evalator2, start2, f36, o36 };
		
		static Vector3[] office37 = new Vector3[] { evalator1, start1, p7, p6, f37, o37 };
		static Vector3[] office38 = new Vector3[] { evalator1, start1, p7, p6, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evalator1, start1, p7, f39, o39 };
		static Vector3[] office40 = new Vector3[] { evalator1, start1, p7, f40, o40 };
		
		static Vector3[] office41 = new Vector3[] { evalator1, start1, p7, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evalator1, start1, p7, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evalator1, start1, p7, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evalator1, start1, f44, o44 };
		static Vector3[] office45 = new Vector3[] { evalator2, start2, f45, o45 };
		static Vector3[] office46 = new Vector3[] { evalator2, start2, f46, o46 };
		static Vector3[] office47 = new Vector3[] { evalator2, start2, f47, o47 };
		static Vector3[] office48 = new Vector3[] { evalator2, start2, f48, o48 };
		
		static Vector3[] office49 = new Vector3[] { evalator2, start2, f49, o49 };
		static Vector3[] office50 = new Vector3[] { evalator2, start2, f50, o50 };
		static Vector3[] office51 = new Vector3[] { evalator2, start2, f53, f51, o51 };
		static Vector3[] office52 = new Vector3[] { evalator2, start2, f53, f52, o52 };
		static Vector3[] office53 = new Vector3[] { evalator2, start2, f53, o53 };
		static Vector3[] office54 = new Vector3[] { evalator2, start2, f53, f54, o54 };		
		static Vector3[] office55 = new Vector3[] { evalator2, start2, f53, f55, o55 };		
		
		static Vector3[] office56 = new Vector3[] { evalator2, start2, f47, f64, f56, o56 };	
		static Vector3[] office57 = new Vector3[] { evalator2, start2, f47, f64, f57, o57 };	
		static Vector3[] office58 = new Vector3[] { evalator2, start2, f47, f64, f58, o58 };
		static Vector3[] office59 = new Vector3[] { evalator2, start2, f47, f64, f59, o59 };
		
		static Vector3[] office60 = new Vector3[] { evalator2, start2, f47, f64, f60, o60 };
		static Vector3[] office61 = new Vector3[] { evalator2, start2, f47, f64, f61, o61 };
		static Vector3[] office62 = new Vector3[] { evalator2, start2, f47, f62, o62 };
		static Vector3[] office63 = new Vector3[] { evalator2, start2, f47, f63, o63 };
		static Vector3[] office64 = new Vector3[] { evalator2, start2, f47, f64, o64 };
		
		static Vector3[] office65 = new Vector3[] { evalator2, start2, f47, f65, o65 };
		static Vector3[] office66 = new Vector3[] { evalator2, start2, f47, f66, o66 };

		
		static Vector3 pos1 = new Vector3 (357.9F, 102.2F, 268.1F);
		static Vector3 pos2 = new Vector3 (335.7F, 78.5F, 254.8F);
		static Vector3 pos3 = new Vector3 (351.9F, 69.1F, 263.6F);
		static Vector3 pos4 = new Vector3 (350.7F, 75.5F, 256.4F);
		static Vector3 pos5 = new Vector3 (335.5F, 76.7F, 264.9F);
		static Vector3 pos6 = new Vector3 (347.0F, 78.4F, 253.7F);
		static Vector3 pos7 = new Vector3 (347.1F, 77.6F, 255.4F);
		static Vector3 pos8 = new Vector3 (333.0F, 73.0F, 262.2F);
		static Vector3 pos9 = new Vector3 (343.4F, 62.9F, 266.7F);
		static Vector3 pos10 = new Vector3 (339.4F, 73.8F, 263.4F);
		static Vector3 pos11 = new Vector3 (314.9F, 80.4F, 240.9F);
		static Vector3 pos12 = new Vector3 (317.8F, 72.4F, 243.2F);
		static Vector3 pos13 = new Vector3 (330.0F, 59.2F, 243.0F);
		static Vector3 pos14 = new Vector3 (321.2F, 74.9F, 248.1F);
		static Vector3 pos15 = new Vector3 (332.0F, 55.9F, 244.5F);
		static Vector3 pos16 = new Vector3 (331.6F, 67.4F, 251.3F);
		static Vector3 pos17 = new Vector3 (348.8F, 79.9F, 252.4F);
		static Vector3 pos18 = new Vector3 (344.8F, 83.1F, 251.5F);
		static Vector3 pos19 = new Vector3 (316.4F, 68.4F, 254.3F);
		static Vector3 pos20 = new Vector3 (338.4F, 82.6F, 249.1F);
		static Vector3 pos21 = new Vector3 (332.8F, 72.7F, 253.0F);
		static Vector3 pos22 = new Vector3 (355.9F, 73.8F, 268.2F);
		static Vector3 pos23 = new Vector3 (325.6F, 85.0F, 252.2F);
		static Vector3 pos24 = new Vector3 (318.5F, 63.8F, 260.2F);
		static Vector3 pos25 = new Vector3 (328.4F, 81.2F, 260.5F);
		static Vector3 pos26 = new Vector3 (295.9F, 63.1F, 242.6F);
		static Vector3 pos27 = new Vector3 (292.2F, 64.8F, 248.4F);
		static Vector3 pos28 = new Vector3 (291.5F, 67.4F, 256.5F);
		static Vector3 pos29 = new Vector3 (299.1F, 68.7F, 255.8F);
		static Vector3 pos30 = new Vector3 (295.9F, 68.5F, 250.6F);
		static Vector3 pos31 = new Vector3 (300.0F, 64.9F, 261.1F);
		static Vector3 pos32 = new Vector3 (289.9F, 60.2F, 248.7F);
		static Vector3 pos33 = new Vector3 (297.4F, 77.5F, 247.6F);
		static Vector3 pos34 = new Vector3 (299.1F, 75.8F, 243.1F);
		static Vector3 pos35 = new Vector3 (291.1F, 79.0F, 256.1F);
		static Vector3 pos36 = new Vector3 (299.8F, 74.8F, 264.5F);
		static Vector3 pos37 = new Vector3 (304.1F, 78.6F, 248.9F);
		static Vector3 pos38 = new Vector3 (310.1F, 77.5F, 246.8F);
		static Vector3 pos39 = new Vector3 (288.1F, 82.4F, 236.0F);
		static Vector3 pos40 = new Vector3 (324.0F, 79.0F, 267.2F);
		static Vector3 pos41 = new Vector3 (337.4F, 90.5F, 257.1F);
		static Vector3 pos42 = new Vector3 (340.2F, 84.1F, 268.3F);
		static Vector3 pos43 = new Vector3 (344.6F, 79.9F, 274.6F);
		static Vector3 pos44 = new Vector3 (347.4F, 72.6F, 277.1F);
		static Vector3 pos45 = new Vector3 (301.7F, 79.3F, 244.8F);
		static Vector3 pos46 = new Vector3 (299.4F, 68.2F, 259.0F);
		static Vector3 pos47 = new Vector3 (277.9F, 68.2F, 252.5F);
		static Vector3 pos48 = new Vector3 (284.8F, 68.2F, 255.6F);
		static Vector3 pos49 = new Vector3 (289.3F, 83.8F, 258.3F);
		static Vector3 pos50 = new Vector3 (232.5F, 67.1F, 258.2F);
		static Vector3 pos51 = new Vector3 (234.6F, 86.2F, 247.4F);
		static Vector3 pos52 = new Vector3 (273.7F, 85.0F, 264.3F);
		static Vector3 pos53 = new Vector3 (268.4F, 90.0F, 258.4F);
		static Vector3 pos54 = new Vector3 (286.9F, 79.6F, 268.9F);
		static Vector3 pos55 = new Vector3 (271.7F, 96.2F, 259.8F);
		static Vector3 pos56 = new Vector3 (273.3F, 87.5F, 261.4F);
		static Vector3 pos57 = new Vector3 (228.1F, 88.6F, 257.1F);
		static Vector3 pos58 = new Vector3 (246.7F, 90.6F, 242.0F);
		static Vector3 pos59 = new Vector3 (280.6F, 83.8F, 245.8F);
		static Vector3 pos60 = new Vector3 (248.2F, 82.7F, 252.5F);
		static Vector3 pos61 = new Vector3 (278.6F, 95.5F, 256.5F);
		static Vector3 pos62 = new Vector3 (279.9F, 79.0F, 243.9F);
		static Vector3 pos63 = new Vector3 (280.1F, 100.2F, 244.4F);
		static Vector3 pos64 = new Vector3 (244.9F, 67.2F, 253.2F);
		static Vector3 pos65 = new Vector3 (287.8F, 82.1F, 251.2F);
		static Vector3 pos66 = new Vector3 (284.6F, 89.7F, 248.4F);

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();

		public Point6_3 ()
		{
			
			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);
			PositnCamera.Add("office21",pos21);
			PositnCamera.Add("office22",pos22);
			PositnCamera.Add("office23",pos23);
			PositnCamera.Add("office24",pos24);
			PositnCamera.Add("office25",pos25);
			PositnCamera.Add("office26",pos26);
			PositnCamera.Add("office27",pos27);
			PositnCamera.Add("office28",pos28);
			PositnCamera.Add("office29",pos29);
			PositnCamera.Add("office30",pos30);
			PositnCamera.Add("office31",pos31);
			PositnCamera.Add("office32",pos32);
			PositnCamera.Add("office33",pos33);
			PositnCamera.Add("office34",pos34);
			PositnCamera.Add("office35",pos35);
			PositnCamera.Add("office36",pos36);
			PositnCamera.Add("office37",pos37);
			PositnCamera.Add("office38",pos38);
			PositnCamera.Add("office39",pos39);
			PositnCamera.Add("office40",pos40);
			PositnCamera.Add("office41",pos41);
			PositnCamera.Add("office42",pos42);
			PositnCamera.Add("office43",pos43);
			PositnCamera.Add("office44",pos44);
			PositnCamera.Add("office45",pos45);
			PositnCamera.Add("office46",pos46);
			PositnCamera.Add("office47",pos47);
			PositnCamera.Add("office48",pos48);
			PositnCamera.Add("office49",pos49);
			PositnCamera.Add("office50",pos50);
			PositnCamera.Add("office51",pos51);
			PositnCamera.Add("office52",pos52);
			PositnCamera.Add("office53",pos53);
			PositnCamera.Add("office54",pos54);
			PositnCamera.Add("office55",pos55);
			PositnCamera.Add("office56",pos56);
			PositnCamera.Add("office57",pos57);
			PositnCamera.Add("office58",pos58);
			PositnCamera.Add("office59",pos59);
			PositnCamera.Add("office60",pos60);
			PositnCamera.Add("office61",pos61);
			PositnCamera.Add("office62",pos62);
			PositnCamera.Add("office63",pos63);
			PositnCamera.Add("office64",pos64);
			PositnCamera.Add("office65",pos65);
			PositnCamera.Add("office66",pos66);

			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
			dictionary.Add("office45",office45);
			dictionary.Add("office46",office46);
			dictionary.Add("office47",office47);
			dictionary.Add("office48",office48);
			dictionary.Add("office49",office49);
			dictionary.Add("office50",office50);
			dictionary.Add("office51",office51);
			dictionary.Add("office52",office52);
			dictionary.Add("office53",office53);
			dictionary.Add("office54",office54);
			dictionary.Add("office55",office55);
			dictionary.Add("office56",office56);
			dictionary.Add("office57",office57);
			dictionary.Add("office58",office58);
			dictionary.Add("office59",office59);
			dictionary.Add("office60",office60);
			dictionary.Add("office61",office61);
			dictionary.Add("office62",office62);
			dictionary.Add("office63",office63);
			dictionary.Add("office64",office64);
			dictionary.Add("office65",office65);
			dictionary.Add("office66",office66);
		}
	}
}

