//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point3_4
	{
		
		static Vector3 evalator = new Vector3 (0.0f, 0.0f, -2.6f);

		static Vector3 start = new Vector3 (0.0f, 0.0f, 0.0f);
		
		static Vector3 f1 = new Vector3 (25.5F, 3.0F, 9.7F);
		static Vector3 f2 = new Vector3 (17.9F, 3.0F, 8.5F);
		static Vector3 f3 = new Vector3 (17.9F, 3.0F, 0.0F);
		static Vector3 f4 = new Vector3 (27.1F, 3.0F, 0.0F);
		static Vector3 f5 = new Vector3 (-15.5F, 3.0F, 0.0F);
		static Vector3 f6 = new Vector3 (-19.4F, 3.0F, 0.0F);
		static Vector3 f7 = new Vector3 (-23.5F, 3.0F, 0.0F);
		static Vector3 f8 = new Vector3 (-27.3F, 3.0F, 0.0F);
		static Vector3 f9 = new Vector3 (-27.3F, 3.0F, 0.0F);
		static Vector3 f10 = new Vector3 (-27.3F, 3.0F, -2.9F);
		static Vector3 f11 = new Vector3 (-27.3F, 3.0F, -6.8F);
		static Vector3 f12 = new Vector3 (-27.3F, 3.0F, -9.7F);
		static Vector3 f13 = new Vector3 (-27.3F, 3.0F, -9.7F);
		static Vector3 f14 = new Vector3 (-23.4F, 3.0F, -9.7F);
		static Vector3 f15 = new Vector3 (-19.4F, 3.0F, -9.7F);
		static Vector3 f16 = new Vector3 (-15.5F, 3.0F, -9.7F);
		static Vector3 f17 = new Vector3 (-15.5F, 3.0F, -9.7F);
		static Vector3 f18 = new Vector3 (-15.59F, 3.0F, -6.8F);
		static Vector3 f19 = new Vector3 (-15.5F, 3.0F, -2.9F);
		static Vector3 f20 = new Vector3 (-11.2F, 3.0F, -0.7F);
		
		static Vector3 o1 = new Vector3 (25.5F, 3.0F, 14.0F);
		static Vector3 o2 = new Vector3 (12.0F, 3.0F, 8.5F);
		static Vector3 o3 = new Vector3 (17.9F, 3.0F, -4.4F);
		static Vector3 o4 = new Vector3 (31.5F, 3.0F, 1.2F);
		static Vector3 o5 = new Vector3 (-15.5F, 3.0F, 4.2F);
		static Vector3 o6 = new Vector3 (-19.4F, 3.0F, 4.2F);
		static Vector3 o7 = new Vector3 (-23.5F, 3.0F, 4.2F);
		static Vector3 o8 = new Vector3 (-27.3F, 3.0F, 4.2F);
		static Vector3 o9 = new Vector3 (-31.6F, 3.0F, 2.6F);
		static Vector3 o10 = new Vector3 (-31.2F, 3.0F, -2.9F);
		static Vector3 o11 = new Vector3 (-31.2F, 3.0F, -6.8F);
		static Vector3 o12 = new Vector3 (-31.7F, 3.0F, -12.4F);
		static Vector3 o13 = new Vector3 (-27.3F, 3.0F, -14.0F);
		static Vector3 o14 = new Vector3 (-23.4F, 3.0F, -14.0F);
		static Vector3 o15 = new Vector3 (-19.4F, 3.0F, -14.0F);
		static Vector3 o16 = new Vector3 (-15.5F, 3.0F, -14.0F);
		static Vector3 o17 = new Vector3 (-11.2F, 3.0F, -12.4F);
		static Vector3 o18 = new Vector3 (-11.6F, 3.0F, -6.8F);
		static Vector3 o19 = new Vector3 (-11.6F, 3.0F, -2.9F);
		static Vector3 o20 = new Vector3 (-11.2F, 3.0F, 3.6F);

		
		static Vector3[] office1 = new Vector3[] { evalator, start, f3, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator, start, f3, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator, start, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator, start, f3, f4, o4 };
		
		static Vector3[] office5 = new Vector3[] { evalator, start, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator, start, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator, start, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator, start, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator, start, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator, start, f8, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator, start, f8, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator, start, f8, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator, start, f8, f13, o13 };
		static Vector3[] office14 = new Vector3[] { evalator, start, f5, f16, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator, start, f5, f16, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator, start, f5, f16, o16 };
		static Vector3[] office17 = new Vector3[] { evalator, start, f5, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[] { evalator, start, f5, f18, o18 };
		
		static Vector3[] office19 = new Vector3[] { evalator, start, f5, f19, o19 };
		static Vector3[] office20 = new Vector3[] { evalator, start, f20, o20 };

		
		static Vector3 pos1 = new Vector3 (294.2F, 78.0F, 240.8F);
		static Vector3 lookat1 = new Vector3 (293.7F, 3.3F, 190.6F);
		static Vector3 pos2 = new Vector3 (286.8F, 77.6F, 247.7F);
		static Vector3 lookat2 = new Vector3 (286.4F, -0.6F, 189.6F);
		static Vector3 pos3 = new Vector3 (295.2F, 82.3F, 240.6F);
		static Vector3 lookat3 = new Vector3 (294.9F, -6.4F, 184.1F);
		static Vector3 pos4 = new Vector3 (280.1F, 82.5F, 242.9F);
		static Vector3 lookat4 = new Vector3 (281.6F, 1.5F, 185.0F);
		static Vector3 pos5 = new Vector3 (283.0F, 83.6F, 232.5F);
		static Vector3 lookat5 = new Vector3 (286.5F, 3.7F, 185.6F);
		static Vector3 pos6 = new Vector3 (284.9F, 77.1F, 236.1F);
		static Vector3 lookat6 = new Vector3 (285.4F, -1.2F, 185.6F);
		static Vector3 pos7 = new Vector3 (280.5F, 87.6F, 228.6F);
		static Vector3 lookat7 = new Vector3 (281.4F, -1.4F, 185.6F);
		static Vector3 pos8 = new Vector3 (291.6F, 74.9F, 238.4F);
		static Vector3 lookat8 = new Vector3 (290.8F, -1.8F, 185.6F);
		static Vector3 pos9 = new Vector3 (277.9F, 76.5F, 255.4F);
		static Vector3 lookat9 = new Vector3 (279.9F, -1.9F, 185.3F);
		static Vector3 pos10 = new Vector3 (279.7F, 89.9F, 233.1F);
		static Vector3 lookat10 = new Vector3 (287.6F, 10.8F, 184.0F);
		static Vector3 pos11 = new Vector3 (285.5F, 82.8F, 247.2F);
		static Vector3 lookat11 = new Vector3 (287.6F, -1.9F, 182.9F);
		static Vector3 pos12 = new Vector3 (285.9F, 90.3F, 235.0F);
		static Vector3 lookat12 = new Vector3 (284.3F, -5.1F, 181.7F);
		static Vector3 pos13 = new Vector3 (278.2F, 96.9F, 231.5F);
		static Vector3 lookat13 = new Vector3 (280.1F, -8.7F, 181.4F);
		static Vector3 pos14 = new Vector3 (292.4F, 72.5F, 254.1F);
		static Vector3 lookat14 = new Vector3 (286.9F, -7.6F, 180.6F);
		static Vector3 pos15 = new Vector3 (290.7F, 70.7F, 253.6F);
		static Vector3 lookat15 = new Vector3 (291.1F, -6.1F, 180.6F);
		static Vector3 pos16 = new Vector3 (291.9F, 87.3F, 242.3F);
		static Vector3 lookat16 = new Vector3 (288.0F, -12.3F, 181.4F);
		static Vector3 pos18 = new Vector3 (288.8F, 72.2F, 246.6F);
		static Vector3 lookat18 = new Vector3 (293.7F, -3.7F, 182.9F);
		static Vector3 pos19 = new Vector3 (278.2F, 75.9F, 240.0F);
		static Vector3 lookat19 = new Vector3 (290.4F, -1.5F, 184.0F);
		static Vector3 pos20 = new Vector3 (290.8F, 76.7F, 244.7F);
		static Vector3 lookat20 = new Vector3 (292.1F, -1.2F, 185.4F);
		
		static Vector3 pos17 = new Vector3 (289.2F, 72.9F, 243.6F);
		static Vector3 lookat17 = new Vector3 (292.0F, -3.2F, 184.0F);

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();
		public Point3_4 ()
		{

			
			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);


			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);
			LookatCamera.Add("office9",lookat9);
			LookatCamera.Add("office10",lookat10);
			LookatCamera.Add("office11",lookat11);
			LookatCamera.Add("office12",lookat12);
			LookatCamera.Add("office13",lookat13);
			LookatCamera.Add("office14",lookat14);
			LookatCamera.Add("office15",lookat15);
			LookatCamera.Add("office16",lookat16);
			LookatCamera.Add("office17",lookat17);
			LookatCamera.Add("office18",lookat18);
			LookatCamera.Add("office19",lookat19);
			LookatCamera.Add("office20",lookat20);
			
			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
		}
	}
}

