//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point6_4
	{
		
		static Vector3 f1 = new Vector3 (49.3F, 1.0F, 14.5F);
		static Vector3 f2 = new Vector3 (45.4F, 1.0F, 14.5F);
		static Vector3 f3 = new Vector3 (41.4F, 1.0F, 14.5F);
		static Vector3 f4 = new Vector3 (37.4F, 1.0F, 14.5F);
		static Vector3 f5 = new Vector3 (37.4F, 1.0F, 14.5F);
		static Vector3 f6 = new Vector3 (37.9F, 1.0F, 11.7F);
		static Vector3 f7 = new Vector3 (37.9F, 1.0F, 7.6F);
		static Vector3 f8 = new Vector3 (33.5F, 1.0F, 4.9F);
		static Vector3 f9 = new Vector3 (37.4F, 1.0F, 4.9F);
		static Vector3 f10 = new Vector3 (41.5F, 1.0F, 4.9F);
		static Vector3 f11 = new Vector3 (45.4F, 1.0F, 4.9F);
		static Vector3 f12 = new Vector3 (49.3F, 1.0F, 4.9F);
		static Vector3 f13 = new Vector3 (49.3F, 1.0F, 4.9F);
		static Vector3 f14 = new Vector3 (48.9F, 1.0F, 7.8F);
		static Vector3 f15 = new Vector3 (48.9F, 1.0F, 11.7F);
		static Vector3 f16 = new Vector3 (49.3F, 1.0F, 14.5F);
		static Vector3 f17 = new Vector3 (10.0F, 1.0F, 4.8F);
		static Vector3 f18 = new Vector3 (6.2F, 1.0F, 4.8F);
		static Vector3 f19 = new Vector3 (2.3F, 1.0F, 4.8F);
		static Vector3 f20 = new Vector3 (-1.7F, 1.0F, 4.8F);
		static Vector3 f21 = new Vector3 (-5.6F, 1.0F, 4.8F);
		static Vector3 f22 = new Vector3 (-5.6F, 1.0F, 4.8F);
		static Vector3 f23 = new Vector3 (-5.35F, 1.0F, 1.97F);
		static Vector3 f24 = new Vector3 (-9.5F, 1.0F, -4.9F);
		static Vector3 f25 = new Vector3 (-5.6F, 1.0F, -4.9F);
		static Vector3 f26 = new Vector3 (-1.7F, 1.0F, -4.9F);
		static Vector3 f27 = new Vector3 (2.3F, 1.0F, -4.9F);
		static Vector3 f28 = new Vector3 (6.2F, 1.0F, -4.9F);
		static Vector3 f29 = new Vector3 (6.2F, 1.0F, -4.9F);
		static Vector3 f30 = new Vector3 (5.7F, 1.0F, -1.9F);
		static Vector3 f31 = new Vector3 (5.7F, 1.0F, 2.0F);
		static Vector3 f32 = new Vector3 (-32.9F, 1.0F, -4.9F);
		static Vector3 f33 = new Vector3 (-36.9F, 1.0F, -4.9F);
		static Vector3 f34 = new Vector3 (-40.8F, 1.0F, -4.9F);
		static Vector3 f35 = new Vector3 (-44.8F, 1.0F, -4.9F);
		static Vector3 f36 = new Vector3 (-48.7F, 1.0F, -4.9F);
		static Vector3 f37 = new Vector3 (-48.7F, 1.0F, -4.9F);
		static Vector3 f38 = new Vector3 (-48.2F, 1.0F, -7.7F);
		static Vector3 f39 = new Vector3 (-48.2F, 1.0F, -11.6F);
		static Vector3 f40 = new Vector3 (-48.6F, 1.0F, -14.5F);
		static Vector3 f41 = new Vector3 (-48.6F, 1.0F, -14.5F);
		static Vector3 f42 = new Vector3 (-44.8F, 1.0F, -14.5F);
		static Vector3 f43 = new Vector3 (-40.8F, 1.0F, -14.5F);
		static Vector3 f44 = new Vector3 (-36.9F, 1.0F, -14.5F);
		static Vector3 f45 = new Vector3 (-36.9F, 1.0F, -14.5F);
		static Vector3 f46 = new Vector3 (-37.4F, 1.0F, -11.7F);
		static Vector3 f47 = new Vector3 (-37.4F, 1.0F, -7.7F);
		static Vector3 f48 = new Vector3 (-5.31F, 1.0F, -1.96F);

		
		static Vector3 o1 = new Vector3 (49.3F, 1.0F, 18.9F);
		static Vector3 o2 = new Vector3 (45.4F, 1.0F, 18.9F);
		static Vector3 o3 = new Vector3 (41.4F, 1.0F, 18.9F);
		static Vector3 o4 = new Vector3 (37.4F, 1.0F, 18.9F);
		static Vector3 o5 = new Vector3 (33.4F, 1.0F, 17.9F);
		static Vector3 o6 = new Vector3 (33.6F, 1.0F, 11.7F);
		static Vector3 o7 = new Vector3 (33.6F, 1.0F, 7.6F);
		static Vector3 o8 = new Vector3 (33.5F, 1.0F, 0.6F);
		static Vector3 o9 = new Vector3 (37.4F, 1.0F, 0.6F);
		static Vector3 o10 = new Vector3 (41.5F, 1.0F, 0.6F);
		static Vector3 o11 = new Vector3 (45.4F, 1.0F, 0.6F);
		static Vector3 o12 = new Vector3 (49.3F, 1.0F, 0.6F);
		static Vector3 o13 = new Vector3 (53.4F, 1.0F, 1.6F);
		static Vector3 o14 = new Vector3 (53.2F, 1.0F, 7.8F);
		static Vector3 o15 = new Vector3 (53.2F, 1.0F, 11.7F);
		static Vector3 o16 = new Vector3 (53.4F, 1.0F, 17.7F);
		static Vector3 o17 = new Vector3 (10.0F, 1.0F, 9.1F);
		static Vector3 o18 = new Vector3 (6.2F, 1.0F, 9.1F);
		static Vector3 o19 = new Vector3 (2.3F, 1.0F, 9.1F);
		static Vector3 o20 = new Vector3 (-1.7F, 1.0F, 9.1F);
		static Vector3 o21 = new Vector3 (-5.6F, 1.0F, 9.1F);
		static Vector3 o22 = new Vector3 (-9.7F, 1.0F, 7.9F);
		static Vector3 o23 = new Vector3 (-9.470001F, 1.0F, 1.97F);
		static Vector3 o24 = new Vector3 (-9.5F, 1.0F, -9.2F);
		static Vector3 o25 = new Vector3 (-5.6F, 1.0F, -9.2F);
		static Vector3 o26 = new Vector3 (-1.7F, 1.0F, -9.2F);
		static Vector3 o27 = new Vector3 (2.3F, 1.0F, -9.2F);
		static Vector3 o28 = new Vector3 (6.2F, 1.0F, -9.2F);
		static Vector3 o29 = new Vector3 (10.2F, 1.0F, -8.0F);
		static Vector3 o30 = new Vector3 (10.0F, 1.0F, -1.9F);
		static Vector3 o31 = new Vector3 (10.0F, 1.0F, 2.0F);
		static Vector3 o32 = new Vector3 (-32.9F, 1.0F, -0.6F);
		static Vector3 o33 = new Vector3 (-36.9F, 1.0F, -0.6F);
		static Vector3 o34 = new Vector3 (-40.8F, 1.0F, -0.6F);
		static Vector3 o35 = new Vector3 (-44.8F, 1.0F, -0.6F);
		static Vector3 o36 = new Vector3 (-48.7F, 1.0F, -0.6F);
		static Vector3 o37 = new Vector3 (-53.0F, 1.0F, -1.8F);
		static Vector3 o38 = new Vector3 (-52.5F, 1.0F, -7.7F);
		static Vector3 o39 = new Vector3 (-52.5F, 1.0F, -11.6F);
		static Vector3 o40 = new Vector3 (-53.0F, 1.0F, -18.0F);
		static Vector3 o41 = new Vector3 (-48.6F, 1.0F, -18.8F);
		static Vector3 o42 = new Vector3 (-44.8F, 1.0F, -18.8F);
		static Vector3 o43 = new Vector3 (-40.8F, 1.0F, -18.8F);
		static Vector3 o44 = new Vector3 (-36.9F, 1.0F, -18.8F);
		static Vector3 o45 = new Vector3 (-32.6F, 1.0F, -18.0F);
		static Vector3 o46 = new Vector3 (-33.0F, 1.0F, -11.7F);
		static Vector3 o47 = new Vector3 (-33.0F, 1.0F, -7.7F);
		static Vector3 o48 = new Vector3 (-9.470001F, 1.0F, -1.96F);

		public static Vector3 start1 = new Vector3 (21.7f, 1.0F, 4.7f);

		public static Vector3 evalator1 = new Vector3 (21.7f, 1.0F, 1.31f);

		public static Vector3 start2 = new Vector3 (-21.4f, 1.0F, -5.0f);
		
		public static Vector3 evalator2 = new Vector3 (-21.4f, 1.0F, -8.39f);

		
		static Vector3[] office1 = new Vector3[] { evalator1, start1, f9, f4, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator1, start1, f9, f4, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator1, start1, f9, f4, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator1, start1, f9, f4, o4 };

		static Vector3[] office5 = new Vector3[] { evalator1, start1, f9, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator1, start1, f9, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator1, start1, f9, f7, o7 };

		static Vector3[] office8 = new Vector3[] { evalator1, start1, f8, o8 };
		static Vector3[] office9 = new Vector3[] { evalator1, start1, f9, o9 };
		
		static Vector3[] office10 = new Vector3[] { evalator1, start1, f10, o10 };
		static Vector3[] office11 = new Vector3[] { evalator1, start1, f11, o11 };
		static Vector3[] office12 = new Vector3[] { evalator1, start1, f12, o12 };
		static Vector3[] office13 = new Vector3[] { evalator1, start1, f13, o13 };

		static Vector3[] office14 = new Vector3[] { evalator1, start1, f12, f14, o14 };
		static Vector3[] office15 = new Vector3[] { evalator1, start1, f12, f15, o15 };
		
		static Vector3[] office16 = new Vector3[] { evalator1, start1, f12, f16, o16 };

		static Vector3[] office17 = new Vector3[] { evalator1, start1, f17, o17 };
		
		
		static Vector3[] office18 = new Vector3[]  { evalator1, start1, f18, o18 };
		
		static Vector3[] office19 = new Vector3[]  { evalator1, start1, f19, o19 };

		static Vector3[] office20 = new Vector3[] { evalator2, start2, f25, f21, f20, o20 };
		static Vector3[] office21 = new Vector3[] { evalator2, start2, f25, f21, o21 };		
		static Vector3[] office22 = new Vector3[] { evalator2, start2, f25, f22, o22 };
		
		static Vector3[] office23 = new Vector3[] { evalator2, start2, f25, f23, o23 };
		static Vector3[] office24 = new Vector3[] { evalator2, start2,  f24, o24 };
		static Vector3[] office25 = new Vector3[] { evalator2, start2, f25, o25 };
		
		static Vector3[] office26 = new Vector3[] { evalator2, start2, f26, o26 };

		static Vector3[] office27 = new Vector3[] { evalator1, start1, f18, f28, f27, o27 };
		static Vector3[] office28 = new Vector3[] { evalator1, start1, f18, f28, o28 };
		static Vector3[] office29 = new Vector3[] { evalator1, start1, f18, f29, o29 };		
		static Vector3[] office30 = new Vector3[] { evalator1, start1, f18, f30, o30 };
		
		static Vector3[] office31 = new Vector3[] { evalator1, start1, f18, f31, o31 };

		static Vector3[] office32 = new Vector3[] { evalator2, start2, f32, o32 };
		
		static Vector3[] office33 = new Vector3[] { evalator2, start2, f33, o33 };
		static Vector3[] office34 = new Vector3[] { evalator2, start2, f34, o34 };
		static Vector3[] office35 = new Vector3[] { evalator2, start2, f35, o35 };
		static Vector3[] office36 = new Vector3[] { evalator2, start2, f36, o36 };
		
		static Vector3[] office37 = new Vector3[] { evalator2, start2, f37, o37 };

		static Vector3[] office38 = new Vector3[] { evalator2, start2, f37, f38, o38 };
		static Vector3[] office39 = new Vector3[] { evalator2, start2, f37, f39, o39 };

		static Vector3[] office40 = new Vector3[] { evalator2, start2, f33, f44, f40, o40 };
		
		static Vector3[] office41 = new Vector3[] { evalator2, start2, f33, f44, f41, o41 };
		static Vector3[] office42 = new Vector3[] { evalator2, start2, f33, f44, f42, o42 };
		static Vector3[] office43 = new Vector3[] { evalator2, start2, f33, f44, f43, o43 };		
		static Vector3[] office44 = new Vector3[] { evalator2, start2, f33, f44, o44 };
		static Vector3[] office45 = new Vector3[] { evalator2, start2, f33, f45, o45 };
		static Vector3[] office46 = new Vector3[] { evalator2, start2, f33, f46, o46 };
		static Vector3[] office47 = new Vector3[] { evalator2, start2, f33, f47, o47 };
		
		static Vector3[] office48 = new Vector3[] { evalator2, start2, f25, f48, o48 };
		
		static Vector3 pos1 = new Vector3 (317.5F, 88.0F, 264.2F);
		static Vector3 lookat1 = new Vector3 (302.0F, 10.5F, 203.0F);
		static Vector3 pos2 = new Vector3 (328.0F, 92.8F, 255.7F);
		static Vector3 lookat2 = new Vector3 (308.8F, 13.1F, 202.6F);
		static Vector3 pos3 = new Vector3 (345.8F, 80.7F, 252.9F);
		static Vector3 lookat3 = new Vector3 (325.2F, 16.4F, 202.6F);
		static Vector3 pos4 = new Vector3 (356.4F, 80.9F, 241.4F);
		static Vector3 lookat4 = new Vector3 (336.2F, 19.9F, 202.6F);
		static Vector3 pos5 = new Vector3 (346.0F, 76.9F, 245.0F);
		static Vector3 lookat5 = new Vector3 (327.4F, 19.8F, 202.5F);
		static Vector3 pos6 = new Vector3 (343.6F, 70.7F, 258.3F);
		static Vector3 lookat6 = new Vector3 (323.3F, 15.5F, 201.2F);
		static Vector3 pos7 = new Vector3 (333.2F, 79.8F, 254.1F);
		static Vector3 lookat7 = new Vector3 (317.8F, 18.1F, 200.0F);
		static Vector3 pos8 = new Vector3 (330.8F, 77.9F, 235.7F);
		static Vector3 lookat8 = new Vector3 (328.9F, 17.9F, 198.6F);
		static Vector3 pos9 = new Vector3 (357.5F, 71.4F, 246.4F);
		static Vector3 lookat9 = new Vector3 (341.5F, 13.4F, 198.6F);
		static Vector3 pos10 = new Vector3 (341.7F, 74.9F, 265.2F);
		static Vector3 lookat10 = new Vector3 (319.1F, 15.4F, 198.6F);
		static Vector3 pos11 = new Vector3 (345.5F, 76.2F, 263.7F);
		static Vector3 lookat11 = new Vector3 (318.0F, 12.5F, 198.6F);
		static Vector3 pos12 = new Vector3 (345.5F, 74.2F, 246.8F);
		static Vector3 lookat12 = new Vector3 (331.8F, 14.2F, 198.6F);
		static Vector3 pos14 = new Vector3 (338.5F, 72.9F, 242.5F);
		static Vector3 lookat14 = new Vector3 (328.5F, 15.0F, 200.1F);
		static Vector3 pos15 = new Vector3 (356.8F, 75.5F, 247.7F);
		static Vector3 lookat15 = new Vector3 (336.8F, 21.3F, 201.2F);
		static Vector3 pos16 = new Vector3 (353.2F, 79.5F, 257.3F);
		static Vector3 lookat16 = new Vector3 (333.1F, 20.3F, 202.4F);
		static Vector3 pos17 = new Vector3 (285.2F, 81.2F, 250.9F);
		static Vector3 lookat17 = new Vector3 (287.4F, 10.8F, 196.1F);
		static Vector3 pos18 = new Vector3 (286.4F, 87.0F, 240.6F);
		static Vector3 lookat18 = new Vector3 (286.4F, 17.8F, 196.1F);
		static Vector3 pos19 = new Vector3 (291.0F, 84.2F, 251.1F);
		static Vector3 lookat19 = new Vector3 (292.8F, 14.5F, 196.1F);
		static Vector3 pos20 = new Vector3 (280.5F, 81.2F, 243.3F);
		static Vector3 lookat20 = new Vector3 (285.0F, 11.2F, 196.1F);
		static Vector3 pos21 = new Vector3 (287.4F, 81.3F, 254.3F);
		static Vector3 lookat21 = new Vector3 (288.5F, 14.8F, 196.1F);
		static Vector3 pos22 = new Vector3 (286.1F, 86.5F, 255.9F);
		static Vector3 lookat22 = new Vector3 (289.7F, 11.3F, 196.0F);
		static Vector3 pos23 = new Vector3 (290.2F, 78.3F, 260.2F);
		static Vector3 lookat23 = new Vector3 (287.1F, 5.7F, 194.5F);
		static Vector3 pos24 = new Vector3 (289.9F, 88.7F, 245.6F);
		static Vector3 lookat24 = new Vector3 (290.2F, 10.4F, 193.0F);
		static Vector3 pos25 = new Vector3 (290.8F, 74.5F, 255.5F);
		static Vector3 lookat25 = new Vector3 (292.4F, 14.3F, 193.0F);
		static Vector3 pos26 = new Vector3 (282.9F, 77.0F, 245.4F);
		static Vector3 lookat26 = new Vector3 (286.1F, 12.3F, 193.0F);
		static Vector3 pos27 = new Vector3 (284.1F, 74.8F, 243.6F);
		static Vector3 lookat27 = new Vector3 (287.9F, 11.2F, 193.0F);
		static Vector3 pos28 = new Vector3 (284.2F, 76.0F, 244.0F);
		static Vector3 lookat28 = new Vector3 (287.0F, 11.7F, 193.0F);
		static Vector3 pos29 = new Vector3 (283.5F, 85.0F, 238.8F);
		static Vector3 lookat29 = new Vector3 (286.5F, 12.1F, 193.1F);
		static Vector3 pos30 = new Vector3 (285.4F, 82.7F, 233.2F);
		static Vector3 lookat30 = new Vector3 (287.0F, 19.0F, 194.1F);
		static Vector3 pos31 = new Vector3 (287.3F, 81.0F, 240.5F);
		static Vector3 lookat31 = new Vector3 (289.4F, 15.3F, 195.0F);
		static Vector3 pos32 = new Vector3 (252.4F, 83.5F, 230.9F);
		static Vector3 lookat32 = new Vector3 (270.3F, 21.7F, 190.2F);
		static Vector3 pos33 = new Vector3 (247.1F, 83.6F, 231.7F);
		static Vector3 lookat33 = new Vector3 (267.1F, 17.6F, 190.2F);
		static Vector3 pos34 = new Vector3 (247.7F, 83.1F, 232.9F);
		static Vector3 lookat34 = new Vector3 (272.2F, 17.8F, 190.2F);
		static Vector3 pos35 = new Vector3 (254.3F, 81.6F, 231.6F);
		static Vector3 lookat35 = new Vector3 (272.3F, 13.7F, 190.2F);
		static Vector3 pos36 = new Vector3 (254.3F, 84.5F, 226.6F);
		static Vector3 lookat36 = new Vector3 (271.2F, 11.6F, 190.2F);
		static Vector3 pos37 = new Vector3 (254.2F, 81.6F, 232.6F);
		static Vector3 lookat37 = new Vector3 (270.5F, 12.5F, 190.1F);
		static Vector3 pos38 = new Vector3 (256.2F, 79.0F, 233.0F);
		static Vector3 lookat38 = new Vector3 (276.3F, 9.6F, 189.4F);
		static Vector3 pos39 = new Vector3 (253.7F, 83.2F, 231.9F);
		static Vector3 lookat39 = new Vector3 (275.8F, 8.6F, 188.7F);
		static Vector3 pos40 = new Vector3 (263.6F, 84.7F, 240.1F);
		static Vector3 lookat40 = new Vector3 (281.8F, 17.3F, 188.0F);
		static Vector3 pos41 = new Vector3 (262.3F, 88.1F, 236.6F);
		static Vector3 lookat41 = new Vector3 (276.9F, 3.0F, 187.9F);
		static Vector3 pos42 = new Vector3 (243.9F, 65.9F, 241.0F);
		static Vector3 lookat42 = new Vector3 (272.6F, 13.4F, 187.9F);
		static Vector3 pos43 = new Vector3 (253.7F, 80.4F, 246.9F);
		static Vector3 lookat43 = new Vector3 (282.9F, 9.6F, 187.9F);
		static Vector3 pos44 = new Vector3 (244.2F, 74.3F, 235.6F);
		static Vector3 lookat44 = new Vector3 (273.6F, 10.1F, 187.9F);
		static Vector3 pos45 = new Vector3 (259.9F, 75.3F, 241.6F);
		static Vector3 lookat45 = new Vector3 (276.9F, 18.4F, 188.0F);
		static Vector3 pos46 = new Vector3 (244.9F, 70.0F, 237.1F);
		static Vector3 lookat46 = new Vector3 (275.2F, 9.8F, 188.7F);
		static Vector3 pos47 = new Vector3 (265.4F, 73.4F, 248.7F);
		static Vector3 lookat47 = new Vector3 (281.5F, 9.7F, 189.4F);
		static Vector3 pos48 = new Vector3 (290.2F, 78.3F, 260.2F);
		static Vector3 lookat48 = new Vector3 (287.1F, 5.7F, 194.5F);
		static Vector3 pos13 = new Vector3 (358.1F, 73.4F, 258.6F);
		static Vector3 lookat13 = new Vector3 (323.7F, 4.1F, 198.8F);


		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point6_4 ()
		{
			
			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);
			LookatCamera.Add("office9",lookat9);
			LookatCamera.Add("office10",lookat10);
			LookatCamera.Add("office11",lookat11);
			LookatCamera.Add("office12",lookat12);
			LookatCamera.Add("office13",lookat13);
			LookatCamera.Add("office14",lookat14);
			LookatCamera.Add("office15",lookat15);
			LookatCamera.Add("office16",lookat16);
			LookatCamera.Add("office17",lookat17);
			LookatCamera.Add("office18",lookat18);
			LookatCamera.Add("office19",lookat19);
			LookatCamera.Add("office20",lookat20);
			LookatCamera.Add("office21",lookat21);
			LookatCamera.Add("office22",lookat22);
			LookatCamera.Add("office23",lookat23);
			LookatCamera.Add("office24",lookat24);
			LookatCamera.Add("office25",lookat25);
			LookatCamera.Add("office26",lookat26);
			LookatCamera.Add("office27",lookat27);
			LookatCamera.Add("office28",lookat28);
			LookatCamera.Add("office29",lookat29);
			LookatCamera.Add("office30",lookat30);
			LookatCamera.Add("office31",lookat31);
			LookatCamera.Add("office32",lookat32);
			LookatCamera.Add("office33",lookat33);
			LookatCamera.Add("office34",lookat34);
			LookatCamera.Add("office35",lookat35);
			LookatCamera.Add("office36",lookat36);
			LookatCamera.Add("office37",lookat37);
			LookatCamera.Add("office38",lookat38);
			LookatCamera.Add("office39",lookat39);
			LookatCamera.Add("office40",lookat40);
			LookatCamera.Add("office41",lookat41);
			LookatCamera.Add("office42",lookat42);
			LookatCamera.Add("office43",lookat43);
			LookatCamera.Add("office44",lookat44);
			LookatCamera.Add("office45",lookat45);
			LookatCamera.Add("office46",lookat46);
			LookatCamera.Add("office47",lookat47);
			LookatCamera.Add("office48",lookat48);

			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);
			PositnCamera.Add("office9",pos9);
			PositnCamera.Add("office10",pos10);
			PositnCamera.Add("office11",pos11);
			PositnCamera.Add("office12",pos12);
			PositnCamera.Add("office13",pos13);
			PositnCamera.Add("office14",pos14);
			PositnCamera.Add("office15",pos15);
			PositnCamera.Add("office16",pos16);
			PositnCamera.Add("office17",pos17);
			PositnCamera.Add("office18",pos18);
			PositnCamera.Add("office19",pos19);
			PositnCamera.Add("office20",pos20);
			PositnCamera.Add("office21",pos21);
			PositnCamera.Add("office22",pos22);
			PositnCamera.Add("office23",pos23);
			PositnCamera.Add("office24",pos24);
			PositnCamera.Add("office25",pos25);
			PositnCamera.Add("office26",pos26);
			PositnCamera.Add("office27",pos27);
			PositnCamera.Add("office28",pos28);
			PositnCamera.Add("office29",pos29);
			PositnCamera.Add("office30",pos30);
			PositnCamera.Add("office31",pos31);
			PositnCamera.Add("office32",pos32);
			PositnCamera.Add("office33",pos33);
			PositnCamera.Add("office34",pos34);
			PositnCamera.Add("office35",pos35);
			PositnCamera.Add("office36",pos36);
			PositnCamera.Add("office37",pos37);
			PositnCamera.Add("office38",pos38);
			PositnCamera.Add("office39",pos39);
			PositnCamera.Add("office40",pos40);
			PositnCamera.Add("office41",pos41);
			PositnCamera.Add("office42",pos42);
			PositnCamera.Add("office43",pos43);
			PositnCamera.Add("office44",pos44);
			PositnCamera.Add("office45",pos45);
			PositnCamera.Add("office46",pos46);
			PositnCamera.Add("office47",pos47);
			PositnCamera.Add("office48",pos48);

			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
			dictionary.Add("office9",office9);
			dictionary.Add("office10",office10);
			dictionary.Add("office11",office11);
			dictionary.Add("office12",office12);
			dictionary.Add("office13",office13);
			dictionary.Add("office14",office14);
			dictionary.Add("office15",office15);
			dictionary.Add("office16",office16);
			dictionary.Add("office17",office17);
			dictionary.Add("office18",office18);
			dictionary.Add("office19",office19);
			dictionary.Add("office20",office20);
			dictionary.Add("office21",office21);
			dictionary.Add("office22",office22);
			dictionary.Add("office23",office23);
			dictionary.Add("office24",office24);
			dictionary.Add("office25",office25);
			dictionary.Add("office26",office26);
			dictionary.Add("office27",office27);
			dictionary.Add("office28",office28);
			dictionary.Add("office29",office29);
			dictionary.Add("office30",office30);
			dictionary.Add("office31",office31);
			dictionary.Add("office32",office32);
			dictionary.Add("office33",office33);
			dictionary.Add("office34",office34);
			dictionary.Add("office35",office35);
			dictionary.Add("office36",office36);
			dictionary.Add("office37",office37);
			dictionary.Add("office38",office38);
			dictionary.Add("office39",office39);
			dictionary.Add("office40",office40);
			dictionary.Add("office41",office41);
			dictionary.Add("office42",office42);
			dictionary.Add("office43",office43);
			dictionary.Add("office44",office44);
			dictionary.Add("office45",office45);
			dictionary.Add("office46",office46);
			dictionary.Add("office47",office47);
			dictionary.Add("office48",office48);
		}
	}
}

