//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point5_4
	{
		
		public static Vector3 start = new Vector3 (-0.1f, 1.5f, -0.4f);
		public static Vector3 evalator = new Vector3 (-0.1f, 1.5f, -3.59f);

		static Vector3 o1 = new Vector3 (25.2F, 2.7F, 13.6F);
		static Vector3 o2 = new Vector3 (11.7F, 2.7F, 8.1F);
		static Vector3 o3 = new Vector3 (17.6F, 2.7F, -4.6F);
		static Vector3 o4 = new Vector3 (31.2F, 2.7F, 0.9F);
		static Vector3 o5 = new Vector3 (-17.8F, 2.9F, 3.8F);
		static Vector3 o6 = new Vector3 (-31.3F, 2.9F, -1.6F);
		static Vector3 o7 = new Vector3 (-25.3F, 2.9F, -14.3F);
		static Vector3 o8 = new Vector3 (-11.8F, 2.9F, -8.8F);

		static Vector3 f1 = new Vector3 (25.2F, 2.7F, 9.3F);
		static Vector3 f2 = new Vector3 (17.6F, 2.7F, 8.1F);
		static Vector3 f3 = new Vector3 (17.6F, 2.7F, -0.3F);
		static Vector3 f4 = new Vector3 (26.9F, 2.7F, -0.3F);
		static Vector3 f5 = new Vector3 (-16.1F, 2.9F, -0.5F);
		static Vector3 f6 = new Vector3 (-27.0F, 2.9F, -0.5F);
		static Vector3 f7 = new Vector3 (-25.3F, 2.9F, -10.0F);
		static Vector3 f8 = new Vector3 (-16.1F, 2.9F, -8.8F);
		
		static Vector3[] office1 = new Vector3[] { evalator, start, f3, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator, start, f3, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator, start, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator, start, f3, f4, o4 };

		static Vector3[] office5 = new Vector3[] { evalator, start, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator, start, f5, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator, start, f5, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator, start, f5, f8, o8 };

		
		static Vector3 pos1 = new Vector3 (292.8F, 76.0F, 253.6F);
		static Vector3 lookat1 = new Vector3 (294.5F, 5.3F, 197.3F);
		static Vector3 pos2 = new Vector3 (299.5F, 69.3F, 246.2F);
		static Vector3 lookat2 = new Vector3 (299.7F, 10.8F, 196.4F);
		static Vector3 pos3 = new Vector3 (294.2F, 70.7F, 248.5F);
		static Vector3 lookat3 = new Vector3 (294.6F, 7.4F, 192.9F);
		static Vector3 pos4 = new Vector3 (285.8F, 84.9F, 232.8F);
		static Vector3 lookat4 = new Vector3 (287.6F, 11.2F, 193.8F);
		static Vector3 pos5 = new Vector3 (286.2F, 74.5F, 231.9F);
		static Vector3 lookat5 = new Vector3 (287.4F, 6.9F, 190.5F);
		static Vector3 pos6 = new Vector3 (271.6F, 73.6F, 225.2F);
		static Vector3 lookat6 = new Vector3 (278.7F, 11.3F, 189.8F);
		static Vector3 pos7 = new Vector3 (276.2F, 74.9F, 225.2F);
		static Vector3 lookat7 = new Vector3 (285.0F, 8.4F, 187.0F);
		static Vector3 pos8 = new Vector3 (264.0F, 76.9F, 227.0F);
		static Vector3 lookat8 = new Vector3 (278.7F, 9.0F, 187.9F);

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();
		public Dictionary<string,Vector3> LookatCamera = new Dictionary<string, Vector3> ();

		public Point5_4 ()
		{
			
			
			LookatCamera.Add("office1",lookat1);
			LookatCamera.Add("office2",lookat2);
			LookatCamera.Add("office3",lookat3);
			LookatCamera.Add("office4",lookat4);
			LookatCamera.Add("office5",lookat5);
			LookatCamera.Add("office6",lookat6);
			LookatCamera.Add("office7",lookat7);
			LookatCamera.Add("office8",lookat8);

			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);


			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
		}
	}
}

