//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Point4_4
	{
		static Vector3 start = new Vector3 (-0.3f, 1.5f, -0.5f);
		static Vector3 evalator = new Vector3 (-0.3f, 1.5f, -4.5f);
		
		static Vector3 o1 = new Vector3 (25.2F, 3.9F, 13.4F);
		static Vector3 o2 = new Vector3 (11.6F, 3.9F, 7.7F);
		static Vector3 o3 = new Vector3 (17.6F, 3.9F, -4.8F);
		static Vector3 o4 = new Vector3 (31.2F, 3.9F, 0.7F);
		static Vector3 o5 = new Vector3 (-17.8F, 3.9F, 3.7F);
		static Vector3 o6 = new Vector3 (-31.4F, 3.9F, -2.0F);
		static Vector3 o7 = new Vector3 (-25.4F, 3.9F, -14.5F);
		static Vector3 o8 = new Vector3 (-11.8F, 3.9F, -9.0F);
		
		static Vector3 f1 = new Vector3 (25.2F, 3.9F, 9.0F);
		static Vector3 f2 = new Vector3 (17.6F, 3.9F, 7.7F);
		static Vector3 f3 = new Vector3 (17.6F, 3.9F, -0.5F);
		static Vector3 f4 = new Vector3 (26.9F, 3.9F, -0.5F);
		static Vector3 f5 = new Vector3 (-16.2F, 3.9F, -0.5F);
		static Vector3 f6 = new Vector3 (-27.1F, 3.9F, -0.5F);
		static Vector3 f7 = new Vector3 (-25.4F, 3.9F, -10.2F);
		static Vector3 f8 = new Vector3 (-16.2F, 3.9F, -9.0F);

		
		static Vector3[] office1 = new Vector3[] { evalator, start, f3, f1, o1 };
		static Vector3[] office2 = new Vector3[] { evalator, start, f3, f2, o2 };
		static Vector3[] office3 = new Vector3[] { evalator, start, f3, o3 };
		
		static Vector3[] office4 = new Vector3[] { evalator, start, f3, f4, o4 };
		
		static Vector3[] office5 = new Vector3[] { evalator, start, f5, o5 };
		static Vector3[] office6 = new Vector3[] { evalator, start, f5, f6, o6 };
		
		static Vector3[] office7 = new Vector3[] { evalator, start, f5, f7, o7 };
		static Vector3[] office8 = new Vector3[] { evalator, start, f5, f8, o8 };

		
		static Vector3 pos1 = new Vector3 (314.4F, 91.4F, 266.3F);
		static Vector3 pos2 = new Vector3 (320.2F, 95.1F, 261.8F);
		static Vector3 pos3 = new Vector3 (311.1F, 88.0F, 255.1F);
		static Vector3 pos4 = new Vector3 (319.4F, 89.6F, 260.4F);
		static Vector3 pos5 = new Vector3 (296.3F, 79.2F, 264.3F);
		static Vector3 pos6 = new Vector3 (286.1F, 92.9F, 259.8F);
		static Vector3 pos7 = new Vector3 (295.2F, 94.4F, 259.5F);
		static Vector3 pos8 = new Vector3 (272.9F, 87.2F, 271.9F);

		
		public Dictionary<string, Vector3[]> dictionary = new Dictionary<string, Vector3[]>();
		public Dictionary<string,Vector3> PositnCamera = new Dictionary<string, Vector3> ();

		public Point4_4 ()
		{

			
			PositnCamera.Add("office1",pos1);
			PositnCamera.Add("office2",pos2);
			PositnCamera.Add("office3",pos3);
			PositnCamera.Add("office4",pos4);
			PositnCamera.Add("office5",pos5);
			PositnCamera.Add("office6",pos6);
			PositnCamera.Add("office7",pos7);
			PositnCamera.Add("office8",pos8);

			dictionary.Add("office1",office1);
			dictionary.Add("office2",office2);
			dictionary.Add("office3",office3);
			dictionary.Add("office4",office4);
			dictionary.Add("office5",office5);
			dictionary.Add("office6",office6);
			dictionary.Add("office7",office7);
			dictionary.Add("office8",office8);
		}
	}
}

